add-ons/plugin.video.vrt.nu

.gitignore
README.md

Adding project readme, hope you like it!

Adding project readme

---

resources/lib/vrtplayer/vrtplayer.py

Overwriting the list_item_title local variable.

---

resources/lib/vrtplayer/urltostreamservice.py

This seems to fix the DNS issue. Hooray !
This fixes #27

Dirty fix for #27

---

plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py

Pull request for https://github.com/pietje666/plugin.video.vrt.nu/issues/51

bugfix drm check on android

---

plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py

Pull request for https://github.com/pietje666/plugin.video.vrt.nu/issues/52

bugfix show subtitles addon setting

---

plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py
plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py
plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py

Quick fix for https://github.com/pietje666/plugin.video.vrt.nu/issues/55

fixed categories and repaired legacy support

---

.travis.yml
Makefile
README.md
plugin.video.vrt.nu/resources/lib/helperobjects/apidata.py
plugin.video.vrt.nu/resources/lib/helperobjects/helperobjects.py
plugin.video.vrt.nu/resources/lib/helperobjects/streamurls.py
plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py
plugin.video.vrt.nu/resources/lib/kodiwrappers/sortmethod.py
plugin.video.vrt.nu/resources/lib/vrtplayer/actions.py
plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacollector.py
plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacreator.py
plugin.video.vrt.nu/resources/lib/vrtplayer/statichelper.py
plugin.video.vrt.nu/resources/lib/vrtplayer/tokenresolver.py
plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py
plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py
plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
pylintrc

Don't merge this yet until I fixed the remaining things.

Fix the broken items from pylint

---

plugin.video.vrt.nu/resources/lib/vrtplayer/streamservice.py

Fix missing sound issue

---

.travis.yml
Makefile
plugin.video.vrt.nu/resources/lib/vrtplayer/statichelper.py
plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py

Handle HTML entities in data

---

plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py
plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py

This PR changes the content of the menu listings so that the directory listing menu fits better with the content shown.

Add more appropriate content to menu listing

---

README.md
plugin.video.vrt.nu/addon.xml

- More badges
- References to the Wiki page
- Clean up of Changelog
- Changelog entries for v1.7.0 release

Prepare for release 1.7.0

---

README.md
plugin.video.vrt.nu/addon.xml
plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po
plugin.video.vrt.nu/resources/language/resource.language.nl_nl/strings.po
plugin.video.vrt.nu/resources/lib/helperobjects/helperobjects.py
plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py
plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacollector.py
plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacreator.py
plugin.video.vrt.nu/resources/lib/vrtplayer/statichelper.py
plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py
plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
pylintrc

- More icons and fanart added
- Simplified artwork using art_dict
- Add more metadata to tvshows and episodes
- Indicate in plot if geo-blocked
- Indicate when a video will disappear in the next 3 months
- Rename replace_newlines_and_strip() to strip_newlines()
- Rename replace_double_slashes_with_https() to add_https_method()
- Improve add_https_method to simply do the right thing
- Turn args calls into kwargs calls for TitleItem

More visual improvements

---

README.md
plugin.video.vrt.nu/addon.xml
plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po
plugin.video.vrt.nu/resources/language/resource.language.nl_nl/strings.po
plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py

This is an attempt to add SOCKS proxy support detection.
I have a **script.module.pysocks** addon ready at: https://github.com/dagwieers/script.module.pysocks

Add SOCKS detection to proxy support

---

plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py

VRT changed something on their website

fixed categories

---

plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py

This was still in my queue. Fully tested.

Simplify the logic

---

README.md
plugin.video.vrt.nu/addon.xml

Finally preparing to the long-awaited v1.7.0 release with lots of improvements.
This fixes #96

Release v1.7.0

---

Makefile
plugin.video.vrt.nu/addon.py

I had this one ready before, but didn't want to slow down any release.

Router simplify

---

Makefile

So next release will be easier ;-)

Include LICENSE and README.md in release

---

plugin.video.vrt.nu/addon.xml
plugin.video.vrt.nu/resources/lib/vrtplayer/streamservice.py

Changes to meet kodi-addon-checker test at https://github.com/xbmc/repo-plugins/pulls

kodi addon checker

---

plugin.video.vrt.nu/addon.py
plugin.video.vrt.nu/resources/lib/helperobjects/apidata.py
plugin.video.vrt.nu/resources/lib/helperobjects/helperobjects.py
plugin.video.vrt.nu/resources/lib/helperobjects/streamurls.py
plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py
plugin.video.vrt.nu/resources/lib/kodiwrappers/sortmethod.py
plugin.video.vrt.nu/resources/lib/vrtplayer/actions.py
plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacollector.py
plugin.video.vrt.nu/resources/lib/vrtplayer/metadatacreator.py
plugin.video.vrt.nu/resources/lib/vrtplayer/statichelper.py
plugin.video.vrt.nu/resources/lib/vrtplayer/streamservice.py
plugin.video.vrt.nu/resources/lib/vrtplayer/tokenresolver.py
plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py
plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
plugin.video.vrt.nu/service.py
plugin.video.vrt.nu/vrtnutests/apihelpertests.py
plugin.video.vrt.nu/vrtnutests/streamservicetests.py
plugin.video.vrt.nu/vrtnutests/vrtplayertests.py

This reverts the incorrect license statements recently added.

Fix incorrect license statements

---

README.md
plugin.video.vrt.nu/addon.xml

Remove inputstream.adaptive requirement for Krypton

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/propose-feature.md

On the Wiki we ask for ideas, so why not provide entry templates for this as well?

Improve GitHub templates, add feature/question

---

resources/lib/vrtplayer/streamservice.py

VRT NU uses [virtual subclips](http://docs.unified-streaming.com/documentation/vod/player-urls.html#virtual-subclips) to provide on demand programs (mostly current affair programs) already from a livestream while or shortly after live broadcasting them. But this feature doesn't work always as expected because Kodi doesn't play the program from the beginning when the ending timestamp of the program is missing from the stream_url. When begintime is present in the stream_url and endtime is missing, we must add endtime to the stream_url so Kodi treats the program as an on demand program and starts the stream from the beginning like a real on demand program.

fix virtual subclips in Kodi

---

.travis.yml
Build-Zip.ps1
Makefile
addon.py
resources/lib/helperobjects/apidata.py
resources/lib/helperobjects/helperobjects.py
resources/lib/helperobjects/streamurls.py
resources/lib/kodiwrappers/kodiwrapper.py
resources/lib/kodiwrappers/sortmethod.py
resources/lib/vrtplayer/actions.py
resources/lib/vrtplayer/metadatacollector.py
resources/lib/vrtplayer/metadatacreator.py
resources/lib/vrtplayer/statichelper.py
resources/lib/vrtplayer/streamservice.py
resources/lib/vrtplayer/tokenresolver.py
resources/lib/vrtplayer/vrtapihelper.py
resources/lib/vrtplayer/vrtplayer.py
service.py
test/apihelpertests.py
test/streamservicetests.py
test/vrtplayertests.py
tox.ini

I didn't realize flake8 tests were not included.

Add flake8 testing

---

pylintrc
resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/helperobjects/helperobjects.py
resources/lib/kodiwrappers/kodiwrapper.py
resources/lib/vrtplayer/streamservice.py
resources/lib/vrtplayer/tokenresolver.py
resources/settings.xml

This pull request solves the Kodi error messages when a user provides wrong or empty login credentials.
Now the user gets an ok dialog with a particular message explaining why login is failing.

improve login handling

---

resources/lib/vrtplayer/vrtapihelper.py

- Fix important issue to URL construction causing seasons to be empty
- Fix episode-titles when shortDescription was an empty string
- Fix logic error
I misinterpreted what the code was doing and optimized it wrong.
This makes it IMO a bit more readable so I would not have made the same mistake.

Fix a few issues I introduced

---

plugin.video.vrt.nu.pyproj
resources/lib/vrtplayer/statichelper.py
resources/lib/vrtplayer/vrtapihelper.py

Kodilabel converter for italic text => could be expanded for other markup as well.

Html to kodilabelconverter

---

resources/lib/vrtplayer/tokenresolver.py

This fixes https://github.com/pietje666/plugin.video.vrt.nu/issues/130

fixed roaming

---

resources/lib/vrtplayer/vrtapihelper.py

This fixes https://github.com/pietje666/plugin.video.vrt.nu/issues/124

fixed seasons

---

resources/lib/vrtplayer/vrtapihelper.py
resources/lib/vrtplayer/vrtplayer.py

This PR adds default fanart/thumbnails for in case the VRT.NU data lacks either.
For a few movies this appears to be already the case.

Set default thumbnails/fanart

---

resources/lib/vrtplayer/vrtapihelper.py

This fixes #146, #147 and #148

Quickfix for urllib3 InvalidURL exception

---

addon.xml
requirements.txt
resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/vrtplayer/metadatacreator.py
resources/lib/vrtplayer/statichelper.py
resources/lib/vrtplayer/streamservice.py
resources/lib/vrtplayer/tokenresolver.py
resources/lib/vrtplayer/tvguide.py
resources/lib/vrtplayer/vrtapihelper.py

- Highlighting the currently playing program (in yellow/red, with *Now on live TV*)
- Introduce dateutil for parsing date/time strings, offers reliability
- Remove the recently introduced **strptime()** function call

Highlight currently playing program using dateutil

---

README.md
addon.xml

We need to make a new release to fix the recent urllib3 breakage.

Prepare for v1.8.0 release

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/settings.xml

Move permalink setting to Advanced tab

---

resources/lib/vrtplayer/vrtapihelper.py

always use urlencoded params

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po

Restore the Subtitles tab

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/kodiwrappers/kodiwrapper.py
resources/lib/vrtplayer/statichelper.py
resources/lib/vrtplayer/tvguide.py
resources/lib/vrtplayer/vrtplayer.py

- Improvements to regexp for formatted text conversion
- Add localized time strings when using strftime()
- Disable menu caching for certain menus

Various improvements and fixes

---

resources/lib/vrtplayer/metadatacreator.py

We only need to compare to 1970-01-01, not sure if this value is actually offset by timezone. I would sincerely doubt it.
This relates to #155

An attempt to fix the tzlocal() issue on Windows

---

test/vrtplayertests.py

The unit tests were not actually testing anything (except a function call) as the used examples were invalid.

Fix unit tests

---

README.md
addon.xml
resources/language/resource.language.nl_nl/strings.po
resources/lib/vrtplayer/statichelper.py
service.py

This is something I wanted to do for some time, feedback welcome.
- Consistently write "VRT NU"
- Imrove intro description and README

Improve the intro text and VRT NU references

---

resources/lib/vrtplayer/vrtapihelper.py

Only use plot outline when title is not recommended.
This allows for better menu listings IMO.

Prefer title over plot outline for label

---

resources/lib/vrtplayer/vrtplayer.py

So it doesn't show *No information available*.

Add category plot

---

addon.py
resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/vrtplayer/actions.py
resources/lib/vrtplayer/vrtapihelper.py
resources/lib/vrtplayer/vrtplayer.py

This PR includes the long-expected channels menu item

Add channels menu

---

resources/lib/vrtplayer/__init__.py
resources/lib/vrtplayer/metadatacreator.py
resources/lib/vrtplayer/tvguide.py
resources/lib/vrtplayer/vrtapihelper.py
resources/lib/vrtplayer/vrtplayer.py

Not all channels were listed. Now use the complete list instead of a hard-coded one.

Add support for radio1 and klara

---

README.md
addon.xml

We are ready to release a new plugin packed with new functionality.

Prepare for v1.9.0 release

---

resources/lib/vrtplayer/streamservice.py

A first simple fix for https://github.com/pietje666/plugin.video.vrt.nu/issues/172

allow Kodi to select lower bandwidth hls streams

---

resources/lib/vrtplayer/metadatacreator.py

been there, done that: https://github.com/pietje666/plugin.video.vrt.nu/commit/f62e73c2a4072fe8f9e99bd591faa6bd8e8b4c0a#diff-f8ede559c7a7f78a75062fda8fa43219L206
This fixes #192

fixes pietje666/plugin.video.vrt.nu#192

---

resources/lib/vrtplayer/metadatacreator.py
test/vrtplayertests.py

Catch if any new programs appear with a yet unknown brand.
This may indicate a new brand/channel was added.

Test known brands

---

README.md
addon.py
resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/vrtplayer/actions.py
resources/settings.xml

This PR implements:
- **Credentials**
- Username
- Password
- **Video**
- Show subtitles
- Use DRM
- ~Internet bandwidth limitation~
- **Interface**
- Permalink in plot
- ~**VRT Radio**~
- ~Install/run VRT Radio~
- **Debug**
- Inputstream Adaptive settings
- Clear VRT cookies
- Log level

Reorganize settings

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/vrtplayer/streamservice.py
resources/settings.xml

Make it clear this only affects inputstream.adaptive.

Improve bandwidth limitation settings

---

Makefile
resources/lib/vrtplayer/tvguide.py
test/tvguidetests.py

This PR fixes a TV guide issue, and includes tests, not nearly enough.

Fix tvguide issue, add unit tests

---

pylintrc
resources/lib/kodiwrappers/kodiwrapper.py

These file changes were missing from the commit, while they were part of
the tests :-/

Fix caching

---

addon.py
resources/lib/helperobjects/helperobjects.py
resources/lib/vrtplayer/streamservice.py
resources/lib/vrtplayer/tokenresolver.py
resources/lib/vrtplayer/tvguide.py
resources/lib/vrtplayer/vrtapihelper.py
resources/lib/vrtplayer/vrtplayer.py
test/apihelpertests.py
test/searchtests.py
test/streamservicetests.py
test/tvguidetests.py
test/vrtplayertests.py

This cleans up the class instances that had underscores in their name.
Now class instances start with an underscore (as private).
This is split of from #213

Clean up object names

---

test/apihelpertests.py
test/searchtests.py
test/streamservicetests.py
test/tvguidetests.py
test/vrtplayertests.py

- Many more mocked functionality
- Various new tests
This is split of #213

Various improvements to unit tests

---

Makefile
resources/lib/kodiwrappers/kodiwrapper.py
resources/lib/vrtplayer/streamservice.py
resources/lib/vrtplayer/tokenresolver.py

- Unquote URLs in log messages
- Add 'clean' target in Makefile
- Change log-levels for common output
- Info: Print URL played
- Verbose: Print all HTTP requests
- Debug: Various other stuff

Assorted fixes

---

resources/lib/kodiwrappers/kodiwrapper.py
resources/lib/vrtplayer/tokenresolver.py
resources/lib/vrtplayer/tvguide.py
resources/lib/vrtplayer/vrtapihelper.py
service.py
test/__init__.py
test/apihelpertests.py
test/searchtests.py
test/streamservicetests.py
test/tvguidetests.py
test/vrtplayertests.py

- Log fixes
- Page-browsing off-by-one error
- Fixes to old class names
- Improve unit tests
This is split off #213

More assorted fixes

---

resources/lib/vrtplayer/vrtapihelper.py

Currently the season-listings look quite boring. This PR adds:
- Thumbnail of a random episode of the season
- Title, geolocked and description to plot

Add season metadata

---

.gitignore
resources/lib/vrtplayer/vrtapihelper.py
test/credentials.json

Fix a newly-introduced bug with long episode-lists

---

resources/language/resource.language.en_gb/strings.po
test/__init__.py

Clean up English translation

---

resources/lib/vrtplayer/tvguide.py

This is a requirement if we want to remember if the cursor was on one of these 3 days.

Create permalinks for today, yesterday and tomorrow

---

resources/lib/kodiwrappers/kodiwrapper.py
resources/lib/vrtplayer/vrtplayer.py

This was still an open issue with the current basic search functionality.

Fix spinner when not search term, or no results

---

resources/lib/vrtplayer/vrtapihelper.py

Another one discovered on Windows 10 / Python 3.

One more unicode fix

---

resources/lib/vrtplayer/__init__.py
resources/lib/vrtplayer/streamservice.py
resources/lib/vrtplayer/vrtplayer.py

- fixes https://github.com/pietje666/plugin.video.vrt.nu/issues/238
- simplify stream selection
- support for uplynk widevine drm
- improved hls substream selection

improve streamservice

---

resources/lib/vrtplayer/tvguide.py

The date was correctly carried over, however the handling of midnight
was not reflected in the displayed date. So before 6AM we assume the EPG
of the day before.

Fix TV guide for midnights

---

addon.py
resources/lib/vrtplayer/statichelper.py
resources/lib/vrtplayer/tvguide.py
resources/lib/vrtplayer/vrtapihelper.py
resources/lib/vrtplayer/vrtplayer.py
test/apihelpertests.py
test/searchtests.py

- A minor fix for next episodes when nothing was found playing now
- A fix where the normal recent listing was filtered from the second page

Another batch of fixes

---

addon.py
resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/vrtplayer/__init__.py
resources/lib/vrtplayer/tvguide.py
resources/lib/vrtplayer/vrtapihelper.py
resources/lib/vrtplayer/vrtplayer.py
test/apihelpertests.py

This PR adds a new 'Soon offline' meny item in the main menu, and a 'My
soon offline' menu in the favorites menu.
This fixes #252

Add Soon offline menu

---

addon.xml
resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/vrtplayer/tvguide.py
resources/settings.xml

- Small fixes to descriptions so it looks better
- Rename Debug setting into Troubleshooting settings
- Fix EPG info in live TV menu when there is no transmission
- Add inpustream.adaptive as an optional requirement
- Reorganize addon settings

Various small fixes

---

.travis.yml
Makefile
addon.xml
resources/lib/kodiwrappers/kodiwrapper.py
resources/lib/vrtplayer/streamservice.py
resources/lib/vrtplayer/tokenresolver.py
resources/lib/vrtplayer/vrtplayer.py
test/streamservicetests.py

- Disable optional inputstream.adaptive dependency
- Change show_ok_dialog() interface
- Avoid unneeded indentation (pythonic style is to avoid indented code)
- Fix streamservice on Python 3 (errors in unit tests)
- Enable streamservicetests in Makefile

Another batch of changes

---

resources/lib/kodiwrappers/kodiwrapper.py

Introduced this just before merging. Bad bad contributor.

Fix small last-minute issue

---

resources/lib/vrtplayer/tvguide.py
test/tvguidetests.py
test/xbmc.py

- a missing log_notice for an HTTP request
- some more tests
- only list 30 days in the past
This fixes #263

Improve TVGuide unit tests

---

addon.xml

Required changes for doing a release.

Prepare for v1.10.0 release

---

addon.xml

So somehow this commit was missing.

Prepare for v1.10.0, the sequel

---

addon.py
addon.xml
resources/lib/favorites.py
resources/lib/kodiwrapper.py
resources/lib/statichelper.py
resources/lib/streamservice.py
resources/lib/tvguide.py
resources/lib/vrtapihelper.py
resources/lib/vrtplayer.py

- Add docstrings to lots of things
- Make favorites specific to what needs it
- Fix favorites cache invalidation
- Rename 'filtered' boolean to 'use_favorites'
- Only access favorites cache when needed
- Only set locale when locale information is needed

Assorted set of fixes

---

resources/lib/__init__.py
resources/lib/favorites.py
resources/lib/kodiwrapper.py
resources/lib/metadatacreator.py
resources/lib/statichelper.py
resources/lib/vrtapihelper.py
resources/lib/vrtplayer.py

- A fix for invalidating caches
- Add more docstrings

Fix invalidate caches, add docstrings

---

addon.py

This is a slightly different fix to avoid favorites in the top menu.

Fix channels/favorites

---

resources/lib/favorites.py

Fix an issue where the add-on crashes when a new user is cancelling the login procedure.

fix crash when xvrttoken is None

---

README.md
addon.xml

Small changes to project description and changelog.

Update add-on information

---

resources/language/resource.language.nl_nl/strings.po
resources/lib/metadatacreator.py
resources/lib/tvguide.py
resources/lib/vrtapihelper.py

- Fix translation of 'Search VRT NU' in Dutch
- Make metadatacreator brands a list

Fix translation and brands

---

README.md
addon.xml
requirements.txt
resources/lib/__init__.py
resources/lib/favorites.py
resources/lib/kodiwrapper.py
resources/lib/metadatacreator.py
resources/lib/router.py
resources/lib/statichelper.py
resources/lib/streamservice.py
resources/lib/tokenresolver.py
resources/lib/tvguide.py
resources/lib/vrtapihelper.py
resources/lib/vrtplayer.py

This adds file doc-strings.
But we should add them to tokenresolver.py, streamservice.py and helperobjects.py.

Add more docstrings

---

resources/lib/__init__.py
resources/lib/favorites.py
resources/lib/helperobjects.py
resources/lib/router.py
resources/lib/streamservice.py
resources/lib/tokenresolver.py
resources/settings.xml
service.py
test/apihelpertests.py
test/favoritestests.py
test/searchtests.py
test/vrtplayertests.py

Changes:
- move all X-VRT-Token functionality from streamservice to tokenresolver
- add new refresh function, speeds up X-VRT-Token refresh
- add docstrings to tokenresolver and streamservice
- reduce duplicate code
- other small changes

improve tokenresolver

---

resources/lib/kodiwrapper.py
resources/lib/router.py
service.py
test/apihelpertests.py
test/favoritestests.py
test/searchtests.py
test/streamservicetests.py
test/tvguidetests.py
test/vrtplayertests.py
test/xbmcaddon.py

We don't need xbmcaddon class in router.py

move xbmcaddon to kodi wrapper

---

.travis.yml
Makefile
resources/language/resource.language.nl_nl/strings.po
resources/lib/favorites.py
resources/lib/streamservice.py
resources/lib/vrtapihelper.py
test/routertests.py
test/xbmc.py
test/xbmcaddon.py
test/xbmcgui.py
test/xbmcplugin.py
test/xbmcvfs.py

These are provisional tests for every possible incoming action.
Let's see how Travis deals with this ;-)

Add router unit tests

---

resources/lib/__init__.py
resources/lib/router.py
resources/lib/vrtapihelper.py
resources/lib/vrtplayer.py

Fixes: https://github.com/pietje666/plugin.video.vrt.nu/issues/293

added function to play latest episode of a tv show

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/streamservice.py

This fixes https://github.com/pietje666/plugin.video.vrt.nu/issues/307

provide user message when VRT NU HLS stream fails with HTTP 415

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/settings.xml

This fixes https://github.com/pietje666/plugin.video.vrt.nu/issues/306

fix empty streaming setting section when inputstream.adaptive is missing

---

resources/lib/statichelper.py
resources/lib/vrtapihelper.py

Fixes https://github.com/pietje666/plugin.video.vrt.nu/issues/299 (without changing the current plugin:// url interface)

always use programUrl (instead of programName)

---

addon.py
pylintrc
resources/lib/__init__.py
resources/lib/kodiwrapper.py
resources/lib/tvguide.py
resources/lib/vrtapihelper.py
resources/lib/vrtplayer.py
test/apihelpertests.py
test/favoritestests.py
test/searchtests.py
test/streamservicetests.py
test/tvguidetests.py
test/vrtplayertests.py

Was planning to do it later, but why not now?

Add urls using routing

---

addon.py
resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/__init__.py
resources/lib/vrtapihelper.py
resources/lib/vrtplayer.py
test/routingtests.py
test/vrtplayertests.py

- Add the "Featured" content menu based on a static list
- A typo in docstring
- Improve categories interface
This fixes #305

Add "Featured content" menu

---

resources/language/resource.language.en_gb/strings.po
resources/lib/__init__.py
resources/lib/kodiwrapper.py
resources/lib/vrtapihelper.py

This fixes pietje666/plugin.video.vrt.nu#321

Add translations for Categories and Featured

---

addon.py
resources/lib/favorites.py
resources/lib/vrtapihelper.py
test/favoritestests.py
test/routingtests.py

- A fix for program titles including a forward slash
- Swapping title and program in the interfaces (start with mandatory field)

Fix issue with program titles including forward slash

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po

This includes:
- fix typos
- grammar and vocabulary improvements

improve user interface strings

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/kodiwrapper.py
resources/lib/vrtplayer.py
resources/settings.xml

- A new kodiwrapper `get_addon_info` method
- Versioned the settings based on add-on version
- Check settings version to add-on version and show v2.0.0 info pop-up

Add a pop-up about the new v2.0.0 impact

---

addon.py
resources/lib/kodiwrapper.py
resources/lib/metadatacreator.py
resources/lib/vrtapihelper.py
test/favoritestests.py
test/routingtests.py

- Change route `/play/id/<publication_id>/<video_id>` into `/play/id/<video_id>/<publication_id>`
- Change route `/play/lastepisode/<program>` into `/play/latest/<program>`
- Added more favorites-examples in unit tests
- Quote slashes in program_title when (un)following

Assorted changes

---

addon.py
resources/lib/vrtapihelper.py

This fixes follow/unfollow favorites with slashes and other special chars

fix quoted favorites

---

README.md
addon.xml
resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po

Prepare for v2.0.0 release

---

addon.py
resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/favorites.py
resources/lib/kodiwrapper.py
resources/lib/tokenresolver.py
resources/settings.xml

- A notification when refreshing favorites
- A notification when clearing VRT tokens
- A notification when invalidating HTTP caches
- A notification when verifying credentials
This fixes #362

Add notifications to actions from settings

---

addon.xml
resources/lib/tvguide.py
resources/lib/vrtapihelper.py
test/test_apihelper.py
test/test_tvguide.py
test/xbmc.py
test/xbmcextra.py
test/xbmcgui.py
test/xbmcplugin.py

- Make the **°** symbol the **ᵛ** symbol
- Color code testing output

Various visual improvements

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/__init__.py
resources/lib/kodiwrapper.py
resources/lib/vrtapihelper.py
resources/lib/vrtplayer.py
resources/settings.xml

- A YouTube entry in the channels menu

Add YouTube support to VRT NU plugin

---

resources/lib/tokenresolver.py

This fixes https://github.com/pietje666/plugin.video.vrt.nu/issues/366

fix roaming when playertoken is expired

---

addon.py
resources/lib/helperobjects.py
resources/lib/kodiwrapper.py
resources/lib/search.py
resources/lib/vrtapihelper.py
test/test_routing.py
test/xbmcgui.py

- A speedup on building listings (by avoiding GUI locking)
- Various sanity fixes
- A bugfix for history search queries
- Setting 'showyoutube' correctly affects listing

Set offscreen=True for ListItems

---

resources/lib/kodiwrapper.py
resources/lib/streamservice.py
resources/lib/vrtapihelper.py
test/xbmc.py

This includes:
- added support for `RunPlugin()`
- Live-to-VOD: if VRT doesn't provide a VOD stream, you still can rewatch programs from the last 24 hours from the archived livestream

improve airdate function

---

resources/lib/vrtapihelper.py

Add banner information to episodes (basically fanart)

---

README.md
addon.xml

Update README and addon.xml for upcoming release.

Prepare for v2.1.0 release

---

resources/lib/metadatacreator.py
resources/lib/vrtapihelper.py

We already use Geo-blocked in the interface, only the code was lacking
in this respect.

Rename Geo-locked to Geo-blocked

---

resources/lib/tokenresolver.py

This fixes roaming on python3 Kodi

fix python3 bug when roaming

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/streamservice.py

This includes:
- fixed bug where phone validation message was not displayed
- new geoblock info message when using VRT NU outside EU

improved roaming handling

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/streamservice.py
resources/lib/tvguide.py
resources/lib/vrtapihelper.py
test/test_search.py

If you press Follow on an episode, you are not actually following the
episode, but the TV show. Make this more clear by adding the TV show
name to the context menu entry.

Add TV show name to context menu

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/addon.py
resources/lib/data.py
resources/lib/tvguide.py
resources/lib/vrtplayer.py
test/test_routing.py
test/test_tvguide.py

This is required to add the TV Guide to the channels menu, by channel.
This fixes #391

Browse TV Guide by channel first

---

README.md
addon.xml
resources/lib/metadatacreator.py

- An update to the README, adding release v2.1.1
- Add plugin.video.youtube plugin as an optional requirement
- A clarification to the use of the 'year' infoLabel

Small updates

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/addon.py
resources/lib/apihelper.py
resources/lib/favorites.py
resources/lib/helperobjects.py
resources/lib/kodiwrapper.py
resources/lib/service.py
resources/lib/streamservice.py
resources/lib/tokenresolver.py
resources/lib/vrtplayer.py
resources/settings.xml
test/userdata/addon_settings.json

- Fixed https://github.com/pietje666/plugin.video.vrt.nu/issues/404
- Reorganised tokenresolver to support idiot-proof credentials handling
- Removed class Credentials to simplify codebase
- Removed check_credentials because this became superfluous
- Improved version check for future use
- Added support for notifications for future use
- Other small changes related to credentials

improve credentials handling

---

resources/lib/tokenresolver.py

This should fix the` StopIteration` error in https://github.com/pietje666/plugin.video.vrt.nu/issues/411

return None if no cookie is found

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/kodiwrapper.py
resources/lib/streamservice.py
resources/lib/tokenresolver.py

- improved error messages for unplayable programs
- fixed small unnoticed roaming bug introduced in https://github.com/pietje666/plugin.video.vrt.nu/commit/09b9e86db3eaaa0c7662a9e8f0c88d480401fc61

fix roaming

---

resources/lib/favorites.py

This fixes the crash in https://github.com/pietje666/plugin.video.vrt.nu/issues/411 but not yet the underlying cause.

never set self._favorites to None

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/addon.py
resources/lib/metadata.py

This pull request implements https://github.com/pietje666/plugin.video.vrt.nu/issues/407

added go to program context menu

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/settings.xml

This moves the menu and http caching into the Troubleshooting settings.

Bring together all caching settings

---

resources/lib/favorites.py

This fixes https://github.com/pietje666/plugin.video.vrt.nu/issues/429

fix my programs menu

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/apihelper.py
resources/lib/metadata.py
resources/lib/tvguide.py

- Fix the ordering of categories and features in en_gb
- Put channel TV guide entry in Bold in channel listing

Fix features/categories ordering in en_gb

---

addon.xml
resources/lib/apihelper.py
resources/lib/tvguide.py

Remove the use of coloured icons as fanart

---

.gitignore
resources/lib/kodiwrapper.py
resources/lib/tokenresolver.py
resources/lib/vrtplayer.py

- Move tokens to tokens/ subdirectory
- Clean up old tokens temporarily

Move tokens to userdata/tokens/

---

resources/lib/metadata.py

- Add the "Go to program" context menu to My recent items and My soon offline
- Move "Follow program" and "Go to program" together

Add "Go to program" context to Favorites

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/kodiwrapper.py
resources/lib/search.py
resources/lib/tvguide.py
resources/lib/vrtplayer.py
test/xbmcplugin.py

This is the final piece in the visual styling of the add-on.
It wasn't always clear in what menu you were visually, this fixes it.

Add breadcrumbs support

---

README.md
addon.xml

Prepare for v2.2.0 release

---

resources/lib/kodiwrapper.py
test/xbmc.py

- rewrote `delete_cached_thumbnail` function using Kodi JSON-RPC API
- fix for unit test

use Kodi JSON-RPC API for delete_cached_thumbnail function

---

README.md
addon.xml

Prepare for v2.2.1 release

---

resources/lib/addon.py
resources/lib/metadata.py

I think it is better to jump to a program showing all episodes of all
seasons. This also fixes the issue of the trailing slash.
This relates to #447

Go to 'allseasons'

---

README.md

It appears that when searching for repositories, having a screenshot in
your README will make that appear in the search-results.
So we need a screenshot ;-)

Add a screenshot to the README.md

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/addon.py
resources/lib/kodiwrapper.py
resources/settings.xml

Reverts pietje666/plugin.video.vrt.nu#455

Revert "Remove Widevine installation (API and settings)"

---

.coveragerc
.travis.yml
README.md
requirements.txt
test/test_favorites.py
test/test_streamservice.py

This adds coverage support to our tests.
It should give a good indication what we are actually testing.

Add coverage support

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/settings.xml

Reverts pietje666/plugin.video.vrt.nu#452

Revert "Add InputStream Helper to Troubleshooting settings"

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po

- Rename "No transmission" to "Retransmissions" (impacts Eén and Canvas)

Rename "No transmission" to "Retransmissions"

---

.gitignore
README.md
addon.xml

Prepare for v2.2.2

---

.coveragerc
.github/codecov.yml

Attempt to disable @codecov-io

Disable codecov-io github bot

---

.github/codecov.yml
.gitignore
resources/language/resource.language.nl_nl/strings.po
resources/lib/data.py
resources/lib/kodiwrapper.py
resources/lib/tvguide.py
resources/lib/vrtplayer.py
test/inputstreamhelper.py
test/test_routing.py

- A very quick fix to breadcrumbs
- Improvements to codecov integration
- Fix a PEP8 issue
- Add a stub inputstreamhelper module
This fixes #451 although improvements are still possible

Improve breadcrumbs

---

test/test_favorites.py
test/test_streamservice.py
test/xbmcaddon.py

This will allow us to do testing using actual credentials on Travis.
This can improve coverage.

Support credentials through environment

---

.travis.yml
test/xbmcextra.py

Still not there with Travis and protected environment variables and
utf-8 output.

Another attempt to fix Travis

---

test/test_routing.py

This adds missing routes and functionality tests.

Add missing routes and functionality

---

resources/lib/apihelper.py
resources/lib/search.py
resources/lib/statichelper.py
resources/lib/tvguide.py
resources/lib/vrtplayer.py

- Make search history manipulations easier
- Add find_entry to search a list of dicts for entry

Simplify code for better coverage

---

resources/lib/kodiwrapper.py
resources/lib/statichelper.py

- Removal of unused functionality

Clean up codebase

---

test/xbmc.py

This will make it possible to test authentication for testing on
US-based Travis infrastructure.

Add proxy support to test framework

---

test/userdata/global_settings.json
test/xbmc.py

Since I don't see it working, add more output statements.

Another test using the proxy variables

---

resources/lib/kodiwrapper.py
test/xbmc.py

More proxy tests for Travis

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/addon.py
resources/lib/kodiwrapper.py
resources/settings.xml
test/test_routing.py
test/userdata/global_settings.json
test/xbmc.py
test/xbmcextra.py
test/xbmcgui.py
test/xbmcplugin.py

This adds support for the new InputStream Helper integration.

Integrate new inputstreamhelper

---

.github/codecov.yml
resources/lib/kodiwrapper.py
test/xbmc.py

This finally fixes proxy support for testing in Travis.

Fix global settings and remove logging

---

test/test_routing.py

This is an attempt to play more streams that work from Travis in US.

Include tests that work for WORLD in Travis

---

resources/lib/kodiwrapper.py

support user paths with unicode characters

---

test/test_favorites.py
test/test_streamservice.py

More various fixes

---

.pylintrc
resources/lib/addon.py
resources/lib/apihelper.py
resources/lib/favorites.py
resources/lib/kodiwrapper.py
resources/lib/metadata.py
resources/lib/search.py
resources/lib/service.py
resources/lib/statichelper.py
resources/lib/streamservice.py
resources/lib/tokenresolver.py
resources/lib/tvguide.py
test/run.py
test/test_apihelper.py
test/test_favorites.py
test/test_kodi.py
test/test_routing.py
test/test_search.py
test/test_streamservice.py
test/test_tvguide.py
test/test_vrtplayer.py
test/userdata/addon_settings.json
test/userdata/global_settings.json
test/xbmc.py
test/xbmcaddon.py
test/xbmcextra.py
test/xbmcgui.py
test/xbmcplugin.py
test/xbmcvfs.py

- More pylint fixes to enable invalid-name and broad-except
- Backport of xbmc framework changes

Fix pylint issues, backport xbmc framework

---

.travis.yml

Append command line run to coverage output.

Small coverage fix

---

.travis.yml
Makefile
resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
test/test_favorites.py
test/test_kodi.py
test/test_streamservice.py
test/userdata/global_settings.json
test/xbmcaddon.py
test/xbmcgui.py

- Compare Dutch translations to English translations
- Fix reported issues in translations
- Backport small improvement in xbmc stub library

Add sanity checks for translations

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/addon.py
resources/lib/apihelper.py
resources/lib/favorites.py
resources/lib/kodiwrapper.py
resources/settings.xml
test/test_routing.py
test/userdata/addon_settings.json
test/xbmcgui.py
test/xbmcvfs.py

- A new setting to manage My favorites
- An API call to manage My favorites
- Fix for addon_settings
This fixes #399

Manage favorites through add-on settings

---

resources/language/resource.language.nl_nl/strings.po
resources/settings.xml
test/userdata/search_history.json
test/xbmc.py
test/xbmcgui.py
test/xbmcplugin.py

- A typo in Dutch translations
- A separator in the settings options
- A backport of xbmc stubs
- Test playing streams by performing a HEAD request

A bunch of small fixes

---

.gitignore
.pylintrc
resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/apihelper.py
resources/lib/favorites.py
resources/lib/helperobjects.py
resources/lib/kodiwrapper.py
resources/lib/metadata.py
resources/lib/tvguide.py
resources/lib/vrtplayer.py
test/test_statichelper.py

This includes changes from the resumepoints PR that are not specific to
resumepoints.

Various fixes

---

README.md
addon.xml
test/xbmcextra.py

Prepare for v2.2.3 release

---

resources/lib/metadata.py

This adds categories to the video metadata.

Add categories as 'tag' in metadata

---

.pylintrc
resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/addon.py
resources/lib/apihelper.py
resources/lib/favorites.py
resources/lib/helperobjects.py
resources/lib/kodiwrapper.py
resources/lib/metadata.py
resources/lib/playerinfo.py
resources/lib/resumepoints.py
resources/lib/search.py
resources/lib/service.py
resources/lib/statichelper.py
resources/lib/tokenresolver.py
resources/lib/tvguide.py
resources/lib/vrtplayer.py
resources/settings.xml
test/test_apihelper.py
test/test_favorites.py
test/test_resumepoints.py
test/test_search.py
test/test_statichelper.py
test/test_vrtplayer.py
test/xbmc.py

- Implementation for resumepoints and caching
- Add support for Watch later
- Add support for resuming episodes
- Push position when stream is paused/stopped
- Implement Watch Later list
Still to do at some point when Kodi supports it:
- Support 'Mark as unwatched' and 'Reset resume position'
This fixes #439

Implement support for resumepoints

---

resources/lib/apihelper.py
resources/lib/data.py
resources/lib/tvguide.py

This is a nice idea from the VTM GO add-on.

Add playing-now information to livetv label

---

test/test_favorites.py
test/test_resumepoints.py
test/test_streamservice.py
test/xbmcaddon.py
test/xbmcextra.py

This makes more sense than keeping it around as a global variable.

Move addon settings into Addon stub

---

resources/lib/playerinfo.py

As this possibly blocks other threads, we shouldn't join threads, exiting the while loop is enough.

no need to join threads

---

addon.xml
resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/kodiwrapper.py
resources/settings.xml

This implements a new Integration tab in the settings.
To do this we had renumber a large part of the Add-on settings.
This fixes #548

Implement Integration settings

---

resources/lib/kodiwrapper.py
resources/lib/vrtplayer.py

This fixes **Container.Refresh may be performed on the wrong container**

Only refresh container if the play action was initiated from it

---

resources/lib/kodiwrapper.py

I noticed this when testing the same logic in my **screensaver.turnoff** add-on.

Fix a logic error

---

resources/lib/metadata.py

This marks episodes as (un)watched in Kodi using VRT NU resumepoints data.

Set Kodi watched status from VRT NU resumepoints

---

resources/lib/kodiwrapper.py
resources/lib/metadata.py
resources/lib/service.py

This fixes some issues when turning watching activity on and off.

Improve enabling and disabling watching acitivity

---

resources/lib/apihelper.py
resources/lib/playerinfo.py
resources/lib/statichelper.py
test/run.py
test/test_apihelper.py
test/test_kodiutils.py
test/test_language.py
test/test_proxy.py
test/test_routing.py
test/test_search.py
test/test_settings.py
test/test_statichelper.py
test/test_tokenresolver.py
test/test_vrtplayer.py
test/xbmc.py
test/xbmcaddon.py
test/xbmcextra.py
test/xbmcgui.py

- More backports from kodi stubs
- Increase randomness of thread id
- Add more integration tests
- Fix retaining addon settings (since we don't write to disk)
- Fix a few corner cases (unhandled errors)

Backport test infrastructure and more tests

---

resources/lib/apihelper.py
resources/lib/kodiutils.py
resources/lib/statichelper.py
test/test_kodiutils.py
test/test_resumepoints.py
test/test_routing.py
test/test_settings.py
test/test_statichelper.py
test/test_streamservice.py
test/test_tokenresolver.py
test/test_vrtplayer.py
test/xbmc.py

- Improve function docs
- Fix boolean types in addon settings
- More tests

More testing

---

resources/lib/service.py

- Fix an issue recently introduced
- Use encode/decode instead of hexlify/unhexlify

Replace hexlify with encode('hex')

---

.travis.yml
resources/lib/apihelper.py
resources/lib/service.py
resources/lib/streamservice.py
resources/lib/tokenresolver.py
resources/lib/tvguide.py

https://github.com/pietje666/plugin.video.vrt.nu/commit/f2166edb85ee00d964ff127068529531fde50c17 broke "Up next" support for Kodi 18 (Python 2) and Kodi 19 with Python 3.6+
https://github.com/pietje666/plugin.video.vrt.nu/commit/b40efb6c0e95f6a344f76b71fbf5829c46869449 broke "Up Next" for Kodi 19 (Python 3)
This pull request fixes "Up Next" support for Python 3.5. Tested on Kodi 19 Python 3.6+ and Kodi 18 Python 2.7+

Python 3.5 fixes

---

Makefile
resources/lib/kodiutils.py
resources/lib/service.py
resources/lib/tokenresolver.py
test/test_apihelper.py
test/test_favorites.py
test/test_kodiutils.py
test/test_language.py
test/test_proxy.py
test/test_resumepoints.py
test/test_routing.py
test/test_search.py
test/test_settings.py
test/test_statichelper.py
test/test_streamservice.py
test/test_tokenresolver.py
test/test_tvguide.py
test/test_vrtplayer.py
test/xbmc.py
test/xbmcvfs.py

This fixes various useless suppressions, and adds missing docstrings.
This fixes #592

Fix pylint useless suppressions

---

resources/lib/resumepoints.py
resources/lib/service.py

This adds asynchronous resumepoint updates.
This is part of #567

Asynchronous resumepoint updates

---

resources/lib/kodiutils.py
resources/lib/metadata.py
resources/lib/playerinfo.py
resources/lib/resumepoints.py
resources/lib/service.py
resources/lib/vrtplayer.py
test/xbmcgui.py

- Add window properties functions
- Store Container.URL in Window property
- Simplify Service class and improve PlayerInfo class
- Rely on Kodi watch status when possible and reduce container updates

Improve playerinfo

---

Makefile
resources/lib/apihelper.py
resources/lib/kodiutils.py

With the better heuristics in Up Next, leave the notification_time up to Up Next.
- Not sending notification_time to Up Next
- Small fix to `set_setting()`

Leave notification_time up to Up Next

---

Makefile
resources/lib/apihelper.py
resources/lib/playerinfo.py

- Makefile typos
- Fix onPlayBackSeek to update last_pos
- Fix issue where self.path could be None
- Better logging wrt. Up Next

Fix remaining issues

---

resources/lib/playerinfo.py

Currently, PlayerInfo processes every play-action in Kodi, this PR ensures that PlayerInfo only processes `plugin://plugin.video.vrt.nu/` paths.

Only process PlayerInfo events from VRT NU

---

Makefile
resources/lib/kodiutils.py

A few fixes coming from Up Next.
VRT NU is still the reference implementation for a lot of stuff :+1:

Backport small improvements

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/apihelper.py
resources/lib/search.py
resources/lib/vrtplayer.py
resources/settings.xml
test/userdata/addon_settings.json

This makes the number of items per page configurable as it impacts
speed/performance and usability.
This fixes #577

Configurable number items per page

---

resources/lib/favorites.py
resources/lib/resumepoints.py
resources/lib/streamservice.py

This should also fix Python 3.5 tests.

Use get_url_json for updating favorites and resumepoints

---

resources/lib/kodiutils.py

I like to know what the source of a json error is.

Add more info to json debug messages

---

resources/lib/favorites.py
resources/lib/kodiutils.py
resources/lib/metadata.py
resources/lib/playerinfo.py
resources/lib/resumepoints.py
resources/lib/search.py
resources/lib/tokenresolver.py
resources/lib/utils.py
test/test_kodiutils.py
test/test_resumepoints.py

- Catch JSON-related exceptions as part of the JSON handling
- Add a fail-return default
- Improve logging as before (show get/post and data)
This is needed to have a working system again :-(
I need to get to the bottom of these issues I am seeing...

Catch and report JSON TypeErrors

---

.gitignore
resources/lib/apihelper.py
resources/lib/favorites.py
resources/lib/kodiutils.py
resources/lib/resumepoints.py

- Improvements to caching logic

Improve caching algorithm

---

resources/language/resource.language.nl_nl/strings.po

https://www.mijnwoordenboek.nl/werkwoord/verversen

Fix spelling

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/playerinfo.py
resources/lib/resumepoints.py

- Simplify overrule_kodi_watched logic
- Implement deleting resumepoint entries
- Add logic for finding entries being watched

Remove entries from resume_points

---

resources/lib/resumepoints.py

Fix still watching

---

resources/lib/playerinfo.py

While testing on Kodi 17, I found out resumepoints didn't work.
This fixes VRT NU resumepoints support on Kodi 17.
FYI "Up Next" is not tested, not supported or available through the Kodi 17 add-on repo anyway

Kodi 17 fixes

---

README.md
addon.xml

Prepare for v2.3.0 release

---

README.md
addon.xml
test/test_apihelper.py
test/test_search.py

Prepare 2.3.0 release again

---

test/test_streamservice.py

Fix integration test

---

resources/lib/apihelper.py

Fix undefined cache_file

---

addon.xml
resources/lib/apihelper.py
resources/lib/data.py
resources/lib/utils.py

This adds support for multiple YouTube links per channel.

Support multiple YouTube links per channel

---

.pylintrc
resources/lib/apihelper.py
resources/lib/favorites.py
resources/lib/kodiutils.py
resources/lib/metadata.py
resources/lib/playerinfo.py
resources/lib/resumepoints.py
resources/lib/search.py
resources/lib/streamservice.py
resources/lib/vrtplayer.py
resources/lib/webscraper.py
test/xbmcaddon.py

This adds a type-option to set_setting so we can force the type when
reading or writing a value.
This fixes #671

Add support for Addon setting types

---

resources/lib/metadata.py

This PR includes fixes to metadata related to Kodi views:
- Do not return season or episode data for oneoff videos

Assorted metadata fixes

---

README.md
addon.xml

Prepare for v2.3.1 release

---

README.md
addon.xml

Prepare for v2.3.2 release

---

requirements.txt
resources/lib/data.py

This fixes https://github.com/pietje666/plugin.video.vrt.nu/issues/683

Add Klara livestream

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/addon.py
resources/lib/kodiutils.py
resources/lib/search.py

This will go to the search query entry form when selecting an existing
search query.

Allow to edit a query from search history

---

test/test_vrtplayer.py

This test was failing again after is was fixed in https://github.com/pietje666/plugin.video.vrt.nu/pull/634
Not sure what is happening...

Fix unit test

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/kodiutils.py
resources/lib/metadata.py
resources/lib/search.py
resources/lib/vrtplayer.py

I detected two problems with the color variables:
- color variables in `strings.po` won't be processed when used as label in `settings.xml`
- changing colors in kodiutils `show_listing` didn't work for playable items when `xbmcplugin.addSortMethod` is used.
This pull request fixes these two problems.

Fix broken colors

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/helperobjects.py
resources/lib/service.py
resources/lib/streamservice.py

There were a few small typos *throughtout* the translations and comments :smile:

Spelling fixes

---

README.md
addon.xml

This updates the location of the repository now that it has moved.

Update location after repo transfer

---

.github/workflows/ci.yml
requirements.txt

- Remove test branch
- Add coveragepy as a requirement

Small fixes to GitHub CI workflow

---

.gitattributes

This removes unneeded files from exported ZIP files.

Remove certain files from ZIP download

---

.github/workflows/addon-check.yml
addon.xml

This prepares the tree and runs kodi-addon-checker on it.

Perform kodd-addon-checker from GitHub CI

---

.github/workflows/ci.yml

This adds coverage support to the SonarCloud integration

Add SonarCloud integration to GitHub CI

---

.github/workflows/ci.yml

Small fix to sonar properties file

---

.github/workflows/ci.yml

One more attempt before I give up.

Sonarcloud final attempt

---

.github/workflows/ci.yml
Makefile
resources/lib/resumepoints.py
resources/lib/utils.py
resources/lib/vrtplayer.py
tests/test_favorites.py
tests/test_resumepoints.py
tests/test_routing.py
tests/test_settings.py
tests/test_streamservice.py
tests/test_utils.py
tests/userdata/addon_settings.json

- A fix in the test framework so feature settings now work again
- New unit tests improve reliability
- More codepaths are now tested

Improve coverage slightly

---

.github/workflows/ci.yml

Because Michaël was right after all.

Add credentials to service testing

---

.github/workflows/addon-check.yml
.github/workflows/ci.yml

This uses the newer options in the proposed pull-request.

Use SonarCloud action and Kodi addon-checker fixes

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/streamservice.py
tests/test_streamservice.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/696

Refresh menu if the stream is not found

---

.github/workflows/status.yml

This adds a new workflow to test the availability of the VRT NU services
as well as the reliability of our own code during frequent testing..

Add status workflow for VRT NU

---

.github/workflows/ci.yml
.github/workflows/status.yml

It currently is missing the requirements

Fixes to status workflow

---

.github/workflows/status.yml

Helps with troubleshooting too.

Run status also on PR and push

---

tests/test_streamservice.py

These booleans originate from before we had real booleans coming from
our settings.

Fix a few more old booleans

---

.github/workflows/ci.yml
.github/workflows/status.yml

This helps to understand what components are affected in the face of failure.

Run all tests always (don't stop on failure)

---

resources/lib/tokenresolver.py

VRT added a cross-site request forgery which caused 403 errors when getting a new user_xvrttoken.

Fix user_xvrttoken

---

README.md
addon.xml

Prepare for v2.3.4 release

---

resources/lib/utils.py
tests/xbmc.py
tests/xbmcgui.py
tests/xbmcvfs.py

These are a few improvements found in other add-on work.

Small backports from work on other add-ons

---

resources/lib/iptvmanager.py

This PR adds support to play programs from the PVR Guide through IPTV Manager.
Needs https://github.com/add-ons/service.iptv.manager/pull/19

Add support for playing from the Guide with IPTV Manager

---

resources/lib/tokenresolver.py

I also cleaned up the flow to fail fast as fast returns make it easier
to understand the code without having to read the whole function.
This fixes the status errors as seen at: https://github.com/add-ons/plugin.video.vrt.nu/runs/712068916?check_suite_focus=true

This fixes an error on missing XSRF-TOKEN cookie

---

resources/lib/tokenresolver.py

VRT changed the name of  the XSRF token. This fixes getting this token again. We need to release this as soon as possible.

Fix XSRF token

---

README.md
addon.xml
resources/settings.xml

Prepare for v2.3.5 release

---

resources/lib/tvguide.py

Iteritems doesn't work on a dict in Python3.

Python3 compability fix

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/addon.py
resources/settings.xml

This will check whether automatic updates are enabled or not.
This relates to #764

Warn if automatic updates is disabled in Kodi

---

tests/checkvrtnu.py

We see issues with the Google Play testing from time to time giving a
false negative. Since I cannot reproduce it, this hopefully will fix it
(assuming this is network-related) or at least provide us with some
insight.

Use requests for HTTP communication

---

resources/lib/kodiutils.py
resources/lib/tokenresolver.py

The add-on uses two kinds of caching, a user-defined ttl based cache for menus and resumepoints and a server-defined "expirationDate" based cache for tokens.
This PR combines the caching functions for these two types of cache in an attempt to simplify the codebase and prepare the caching functions for a future "streamcache".

Integrate token cache in kodiutils

---

tests/checkvrtnu.py

Google changed javascript and it failed.

Fix app release check

---

tests/xbmc.py
tests/xbmcaddon.py
tests/xbmcplugin.py
tests/xbmcvfs.py

It is probably a good idea to check for argument types and values where
this is possible to fail fast.

Add asserts to stubs

---

resources/lib/apihelper.py
resources/lib/vrtplayer.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/388

Extend soon offline menu to seven days

---

.github/workflows/addon-check.yml
.github/workflows/ci.yml

- Using upstream sonarcloud action with new functionality
- Revert back to using kodi-addon-checker pip package

Clean up workflows

---

addon.xml
resources/lib/apihelper.py
tests/test_routing.py

This properly indents addon.xml and adds missing coverage.
To prepare the upcoming Kodi library support.

Improve coverage

---

addon.xml

This should have been done a long time ago.

Add mediaminister to list of authors

---

resources/lib/kodiutils.py
resources/lib/metadata.py

Since recently the VRT NU metadat contains poster information.
And this looks really nice in the Kodi interface!

Add poster support

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/data.py
resources/lib/metadata.py
tests/test_vrtplayer.py

The Status check reported today that we have a new category Nostalgia in
VRT NU. This updates everything to support this.
Also ensure we do not throw an exception when a new category is missing
from the categories list.

Add new category Nostalgia

---

README.md
addon.xml

Prepare for v2.4.1 release

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/settings.xml

* Allow installing IPTV Manager now it's in the repo.
* Remove `(experimental)` label

Allow to install IPTV Manager from the settings

---

resources/lib/apihelper.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/835

Support programs with more than 10 seasons

---

resources/lib/utils.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/838

Remove '.html' from short programUrl

---

README.md
addon.xml

Prepare for v2.4.2 release

---

Makefile
README.md
requirements.txt
resources/lib/iptvmanager.py
resources/lib/kodiutils.py
tests/test_vrtplayer.py
tests/xbmcaddon.py
tests/xbmcextra.py
tests/xbmcgui.py
tests/xbmcplugin.py
tests/xbmcvfs.py

- A fix to multizip in Makefile for Bash
- Implement Kodi v19 xbmcvfs.translatePath() support
- Various improvements to the xbmc stubs

Various backports

---

resources/lib/kodiutils.py
resources/lib/streamservice.py

This includes:
- Add livestream cache for faster zapping

Add livestream cache

---

resources/lib/streamservice.py

This fixes a problem with a bad licence url and an expired VUDRM token when watching recently broadcasted current affair programs with **Widevine DRM enabled**.
This is tested with VRT Journaal, Terzake, De Afspraak in the **Most Recent** menu and it works.
- Het Journaal Update: **18h04-18h11**
- Het Journaal 19u: **19h00-19h43**
- Terzake: **20h00-20h30**
- De Afspraak: **20h30-21h20**
- Het Journaal Laat: **21h47-22h02**

Fix livestream cache

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/apihelper.py
resources/lib/data.py
resources/lib/metadata.py
resources/lib/vrtplayer.py
tests/test_vrtplayer.py

- Checks if featured categories exist from VRT NU Search API
- Add featured content from VRT NU Homepage

Improve featured menu

---

resources/lib/metadata.py

This fixes the Most Recent menu when the necessary apidata is empty.

Fix getting plotoutline

---

resources/lib/tokenresolver.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/882

Fix getting age restricted content

---

resources/lib/apihelper.py
resources/lib/kodiutils.py
resources/lib/metadata.py
resources/lib/playerinfo.py
resources/lib/resumepoints.py
resources/lib/webscraper.py
tests/test_resumepoints.py

Fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/914

Fix resumepoints

---

resources/lib/addon.py
resources/lib/favorites.py
resources/lib/metadata.py
resources/lib/utils.py
resources/lib/vrtplayer.py
tests/test_favorites.py
tests/test_routing.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/912

Fix favorites

---

resources/lib/apihelper.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/951

Fix season infolabels

---

resources/lib/addon.py
resources/lib/apihelper.py
resources/lib/tvguide.py
resources/lib/vrtplayer.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/954

Fix playing from tv guide

---

resources/lib/utils.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/969

Fix image url formatting

---

resources/lib/apihelper.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/988

Fix program queries with single chars

---

resources/lib/apihelper.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/994

Fix program queries with digits

---

resources/lib/kodiutils.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/1004

Don't fail on bbcode colouring

---

resources/lib/favorites.py
resources/lib/kodiutils.py
resources/lib/resumepoints.py

Another VRT MAX api change.
Not a fix, this is just working around the http error.

Fix http errors for resumepoints and favorites

---

resources/lib/resumepoints.py

This includes:
- Disable watchlater list: It seems VRT removed this function
- Get continue episode list using GraphQL

Disable watchlater list

---

resources/language/resource.language.en_gb/strings.po
resources/language/resource.language.nl_nl/strings.po
resources/lib/addon.py
resources/lib/apihelper.py
resources/lib/kodiutils.py
resources/lib/metadata.py
resources/lib/playerinfo.py
resources/lib/resumepoints.py
resources/lib/tokenresolver.py
resources/lib/tvguide.py
resources/lib/vrtplayer.py
tests/test_resumepoints.py
tests/test_routing.py
tests/test_settings.py

VRT removed the watch later functionality.

Remove watchlater

---

resources/lib/addon.py
resources/lib/streamservice.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/1064

Restore /play/url/ entrypoint

---

.github/workflows/ci.yml
resources/lib/api.py
resources/lib/apihelper.py
tests/checkvrtmax.py

* Added Python 3.10 to tests
* FIx pylint warnings and add missing timeout

Support Python 3.10

---

resources/lib/addon.py
resources/lib/api.py
resources/lib/apihelper.py
resources/lib/vrtplayer.py
tests/test_routing.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/1097

Fix paging for episode lists

---

resources/lib/streamservice.py
resources/lib/tokenresolver.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/1119

Fix streaming

---

resources/lib/api.py

This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/1126

Fix seasons and featured menu

---

resources/lib/utils.py
tests/test_utils.py

Update utils.py to support additional vrtmax cases
