resources/language/resource.language.en_gb/strings.po
=> Fixes #4 Name of channel "Eén" should capitalized

resources/lib/vrtplayer/metadatacollector.py, resources/lib/vrtplayer/metadatacreator.py, resources/lib/vrtplayer/vrtplayer.py
Fixes issue #1.
Prepended the title of each video item (Kodi list items) with the broadcast date (release date).
This makes videos much easier to identify, as it sometimes takes several hours before a new episode comes available online.
At the moment, I'm using the date format as it is displayed in the tag with the `tile__broadcastdate--mobile` class. As a further improvement, we can (should?) parse this date using [`datetime.strptime()`][1], and format it in another, less ambiguous format (e.g. "25 JUN 2017" or "2017-06-25" for today).
Hope you like my contribution!
[1]: https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior
=> Added video broadcast date to video items

resources/lib/vrtplayer/vrtplayer.py
VRT is now using a CDN (vualto / akamai) and is using new stream links (https://services.vrt.be/videoplayer/r/live.json). The old links still work, however when there is lots of traffic / viewers Kodi has problems keeping up with the stream. The CDN links should fix that.
=> Fix stream urls

plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po, plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py, plugin.video.vrt.nu/resources/lib/vrtplayer/streamservice.py, plugin.video.vrt.nu/resources/lib/vrtplayer/urltolivestreamservice.py, plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py, plugin.video.vrt.nu/resources/settings.xml
Hello,
I added support for the DRM-protected 720p livestreams. You can switch DRM on in the addon settings.
You need the latest Kodi 18 and inputstream.adaptive with libwidevinecdm.
=> support for drm livestreams

plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py
I edited UrlToStreamService class to provide the stream urls faster. For compatibility with older Kodi installations without inputstream.adaptive or DRM-support, the highest quality HLS-variant is directly provided cause the standard Kodi-player is fairly slow to select the HLS-variants.
So, inputstream.adaptive or DRM isn't necessarily required.
=> faster stream selection

.gitignore, Makefile
Since the addon files are one level deeper, we can't just use a GitHub ZIP file of the current branch to test any branch (like new PRs).
This Makefile makes it quite simple, just run 'make' and a new (unique) ZIP file is created. It can help to test-drive new PR's or bisect to find when an issue was introduced.
```bash
[dag@moria plugin.video.vrt.nu]$ make
= Building new package
rm -f plugin.video.vrt.nu-1.6.0-a25e4d8.zip
zip -qr plugin.video.vrt.nu-1.6.0-a25e4d8.zip plugin.video.vrt.nu -x plugin.video.vrt.nu.pyproj vrtnutests
= Successfully wrote package as plugin.video.vrt.nu-1.6.0-a25e4d8.zip
```
=> Add Makefile to build zip files easily

.travis.yml, Makefile, README.md, plugin.video.vrt.nu/resources/lib/helperobjects/streamurls.py, plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py, plugin.video.vrt.nu/vrtnutests/apihelpertests.py, plugin.video.vrt.nu/vrtnutests/urltostreamservicetests.py, requirements.txt
- Running unit tests from Travis
- Improvements to Makefile to add `make unittest`
- A requirements.txt file (this also makes GitHub make dependencies with other projects)
- A Travis badge on the README
- 2 fixes for Python 3 compatibility (wrt. urlencode and urljoin)
- A fix that broke the addon (related to use_inputstream_adaptive)
=>  Add unit tests

Makefile, plugin.video.vrt.nu/addon.py, plugin.video.vrt.nu/resources/lib/helperobjects/apidata.py, plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py, plugin.video.vrt.nu/resources/lib/vrtplayer/tokenresolver.py, plugin.video.vrt.nu/resources/lib/vrtplayer/urltostreamservice.py
This PR also makes the following changes:
- Ensure we import either the Python3 or Python2 libraries for `urljoin()` and `parse_qsl`
- Make the tox environments configurable when using `make test`.
One can now do: `make test ENVS=py26,py27,py36,py37`
- Fix issues I introduced when removing access to private variables
- Run the tests before building a ZIP file (to avoid future issues like the previous one)
With this PR, [a Python3 *BeautifulSoup* package](https://mirrors.kodi.tv/addons/migration/script.module.beautifulsoup4/) and a newer *inputstreamhelper* package (or some fixes) the VRT.NU addon works on Kodi 18.2 with native Python3 !
This fixes #66
=> A few more PY3 fixes

plugin.video.vrt.nu/resources/language/resource.language.en_gb/strings.po, plugin.video.vrt.nu/resources/language/resource.language.nl_nl/strings.po, plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
This PR includes the following ideas:
- Add logo/description for the main menu items (A-Z, Categories, Live TV, Most recent)
- ~Add category description (just repeat category name)~
=> Visual improvements to menu listings

plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py, plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
This PR ensures that the order of the items on the main menu, and the live TV menu is static and not sorted alphabetically. This is important to ensure users can expect entries to be in the same location no matter what language was selected.
The order of the menu items is now listed very specifically, with the more important/used items at the top. (A bit like the Netflix plugin)
=> Keep static order in main/live menu

plugin.video.vrt.nu/resources/lib/helperobjects/helperobjects.py, plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py, plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py, plugin.video.vrt.nu/vrtnutests/streamservicetests.py
This PR adds directory icons and fanart to all menus.
Beware that the fanart is the same as the thumbnail, which for categories, tvshows and main menu could be done better (by using the parent's thumbnail, or no fanart at all).
But even with the thumbnail as fanart, IMO it looks better.
Also the icons do not work at the moment...
=> Add fanart to menus

.travis.yml, Makefile, plugin.video.vrt.nu/addon.py, plugin.video.vrt.nu/resources/lib/helperobjects/helperobjects.py, plugin.video.vrt.nu/resources/lib/vrtplayer/statichelper.py, plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py, plugin.video.vrt.nu/vrtnutests/vrtplayertests.py
Since we now have the live stream screenshot as fanart, we can safely turn back to text-based icons for channels, so that adding it to favourites works properly again.
=> Restore the channel thumbnail to text-based thumbnail

plugin.video.vrt.nu/resources/lib/vrtplayer/streamservice.py
VRT makes use of virtual subclips to provide live broadcast current affairs programs in an "on demand" context. For instance: "Het Journaal" in the "Most recent" menu uses this feature.
This fixes availability of current affair programs during and immediately after the live broadcast for users who don't use inputstream.adaptive
=> hls streams: support virtual subclips (vbegin and vend parameters)

plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py, plugin.video.vrt.nu/resources/lib/vrtplayer/streamservice.py
We don't have to check if inputstream.adaptive is installed when selecting the mpeg dash drm stream because inputstreamhelper is doing this and gives the user a message if it is not installed.
=> let inputstreamhelper handle inputstream.adaptive status

plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py
Currently we use the same thumbnail and fanart for video listings, but we can actually show something different in most cases. So that the background shows the programImageUrl and it sticks around when browsing the episodes.
This also adds fanart to season listings.
This PR also increases the number of recent items to 100.
=> Improve thumbnail/fanart information

plugin.video.vrt.nu/resources/lib/kodiwrappers/kodiwrapper.py, plugin.video.vrt.nu/resources/lib/vrtplayer/streamservice.py, plugin.video.vrt.nu/resources/lib/vrtplayer/tokenresolver.py, plugin.video.vrt.nu/resources/lib/vrtplayer/vrtapihelper.py, plugin.video.vrt.nu/resources/lib/vrtplayer/vrtplayer.py
Make every dictionary lookup use get() which doesn't raise an exception
when missing. (If JSON returns something unexpected, or web scraping
fails unexpectedly)
We still have to look for each dictionary lookup what we should return
if the lookup fails. By default it returns None, which sometimes is
fine, but in some cases we better return an empty list or an empty dict.
Some parts now will undoubtedly fail because of None values where it
would have failed Kodi before.
In some cases a missing title would be better replaced with e.g. 'N/A'
or 'video #X' so the listing would still work. Either a complete review
is necessary, or future brokeness will guide us to make better decisions
;-)
This fixes #35
=> Make code more robust

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/vrtplayer/vrtplayer.py
This adds "Geo-locked" to the Live streams plot description.
It also adds a different (translated) plot per channel, which we can improve on later too.
This implements a suggestion from #130
=> Add Geo-locked to live streams

resources/lib/vrtplayer/statichelper.py, resources/lib/vrtplayer/vrtapihelper.py
This adds support for all (known) HTML elements and converts it to Kodi formatted text.
It includes very specific conversions that relate to VRT.NU formatting (wrt. newlines and paragraphs).
This relates to #129 
This fixes #128 
PS To verify proper output, look at the output of *"Winteruur met Fatma Taspinar"* or *"Winteruur met Abdelkader Benali"*.
=> Sanitize all HTML elements

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po
Ensure 'live' is in the menu entry name so that when these entries are
added to favourites, they clearly indicate this brings you to the live
channels.
At some point we will add listings per channel, so the distinction is
worthwhile in the future (the sooner the better for new users).
=> Add 'live' to live TV channels

addon.py, resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/kodiwrappers/sortmethod.py, resources/lib/vrtplayer/metadatacreator.py, resources/lib/vrtplayer/streamservice.py, resources/lib/vrtplayer/tokenresolver.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py
This implements more sensible episode names and sort order based on program displayOptions.
- ~Implementation of *showSeason* (so don't show seasons if this is set to False)~
- Using *broadcast date* when *showBroadcastDate* was set
- ~Using *S0XE0Y* format when *showSeason* is disabled~
- Add sorting methods in GUI listing options
- ~Implementation of sort order (ascending/descending) in GUI based on programType *reeksaflopend*/*reeksoplopend*~
- Implementation of sort by *date added* for recent items
- Implementation for programType *daily* and *oneoff*
- Cleanup related to sort method's.
This fixes #126 as good as can be.
=> Improve episode listing and sort order

resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py
Using SORT_METHOD_UNSORTED is better than using SORT_METHOD_NONE as it appears in the sort order list as 'Default'. So this makes it a bit more consistent, people can go back to the original/preferred sort order.
Also comment out non-functional code.
I removed sort order "Date" as it doesn't work as people would expect, and is confusing as we also have "Date added". The only thing remaining is to make sort order "Name" and sort order "Title" do the right thing (Title should sort discarding the date/episode prefix we added ourselves).
=> Restore the "Default' sort order

resources/lib/vrtplayer/streamservice.py
This change avoids a HTTP request for every menu change in Kodi and
speeds up browsing through menus.
=> Avoid getting license url when unneeded

pylintrc, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/vrtplayer/metadatacreator.py, resources/lib/vrtplayer/statichelper.py, resources/lib/vrtplayer/vrtapihelper.py, resources/settings.xml
There's no metadata in the video_dict for external URLs (there really should be though).
So I am adding the shortened permalink to the end of the plot, this could be useful if this episode/video needs to be played through another means (e.g. because Kodi has an issue or the addon fails somehow).
=> Add permalink to video plot

resources/lib/vrtplayer/streamservice.py
Little improvement: We only need the widevine license url, when getting a widevine drm stream
=> only get widevine license url when getting widevine drm streams

addon.py, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/actions.py, resources/lib/vrtplayer/metadatacreator.py, resources/lib/vrtplayer/statichelper.py, resources/lib/vrtplayer/tvguide.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py
So the approach is this:
- You select the day (today, yesterday, ...)
- We can go back 1 month, and forward 1 week
- Giving a long list of 40 entries is not a good interface though
- You select the channel
- You get a TV listing for the whole day, with links to play available episodes from the TV-guide
TODO:
- Translate some strings, clean up the interface somewhat
=> Add a TV guide menu entry

resources/lib/vrtplayer/metadatacreator.py
This was required for the plugin to work again on Windows.
It is a quickfix, a better solution is needed.
=> Fix for tzlocal() on Windows

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/vrtplayer/streamservice.py, resources/lib/vrtplayer/vrtplayer.py
These two streams were still on my wishlist.
=> Add Studio Brussel and MNM live streams

addon.py, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/__init__.py, resources/lib/vrtplayer/metadatacreator.py, resources/lib/vrtplayer/streamservice.py, resources/lib/vrtplayer/tvguide.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py, test/vrtplayertests.py
- Provide better Studio names
- Fall back to hardcoded list of CATEGORIES if web-scraping fails
- A hardcoded list of channels (both tv as radio)
- Clean up of codebase to use both CHANNELS and CATEGORIES
- Generate list of live streams from CHANNELS
- Include unit test to ensure hard-coded CATEGORIES is identical to web-scraped list
We could now run our tests on an hourly basis to confirm that category-listing scraping works and our internal representation is correct and complete.
This implements https://github.com/pietje666/plugin.video.vrt.nu/issues/57#issuecomment-483650787
PS The fallback mechanism does not support thumbnails. We could do that, but I expect the thumbnails to change more often.
=> Implement fallback for Categories web-scraping

resources/lib/vrtplayer/__init__.py, resources/lib/vrtplayer/streamservice.py, resources/lib/vrtplayer/vrtplayer.py
This implements vualto live stream support (by video_id) for streams
that do not rely on web scraping, but also implements a fallback
mechanism in case web scraping fails.
This is the last piece to get rid of any reliance on web scraping.
Users everywhere rejoice !
This fixes #57
=> Fallback for live streams when web scraping fails

resources/lib/vrtplayer/__init__.py, resources/lib/vrtplayer/streamservice.py, resources/lib/vrtplayer/vrtplayer.py
`vualto_een`, `vualto_canvas`, `vualto_ketnet` and `vualto_sporza` are deprecated video_id's since VRT geoblocks live streams. This was the main cause the previous commit was failing on hls streams.
Other changes:
- removed direct mpeg_dash option, for two reasons:
- every VRT stream is available through vualto video aggregator api
- in the past direct stream urls changed several times a year at unpredictable times
- separated web scraping function, so it's easier and more failsafe to fix
- added an error message to Kodi log when web scraping fails
- centralized `api_data` manipulations in `_get_api_data` function
=> improve streamservice

addon.py, resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/metadatacreator.py, resources/lib/vrtplayer/streamservice.py, resources/lib/vrtplayer/tokenresolver.py, resources/lib/vrtplayer/tvguide.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py, test/vrtplayertests.py
- ~Replacing **requests** module with **urllib2** (except for tokenresolver)~
- Move infrequently used libraries into local context (i.e. json, inputstream, etc...)
- Move streamservice and tokenresolver out of addon.py
- Remove unused `addon.getAddonInfo('path')` from classes
~This fixes #169 as it speeds up menus drastically on Raspberry Pi.~
Remaining problems that needs fixing before we can consider this:
- Module **urllib2** does not exist on Python 3 ! (So we need a wrapper ?)
- Playback still starts slow due to tokenresolver using **requests**.
- Breaks proxy support currently
IMO We should be fixing the root cause instead.
=> Improve module imports to speed up operation

addon.py, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/vrtplayer/actions.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py, test/vrtplayertests.py
This PR lists recent items 50 at a time, and adds a 'More...' button at the end.
=> Add page-browsing to recent menu

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/streamservice.py, resources/lib/vrtplayer/tokenresolver.py, resources/lib/vrtplayer/tvguide.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py, resources/settings.xml
Since there is something corrupting my language strings in Kodi, I started investigating and our plugin is using the wrong range for the string ids. This fixes it.
Not sure if our plugin was the cause though, time will tell.
=> Use different string ids to not corrupt Kodi

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiwrappers/kodiwrapper.py, resources/settings.xml
Attempt to use max_bandwidth for inputstream.adaptive.
This will select the lowest value of both the global network max_bandwidth as well as our own max_bandwidth setting.
This fixes #172
=> Implement inputstream.adaptive.max_bandwidth

addon.xml
This ought to speed up using the addon as it avoids loading the python
interpreter and libraries.
I don't see a noticable speed difference for v1.9.0 though.
=> Enable 'reuselanguageinvoker'

addon.py, resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/streamservice.py, resources/lib/vrtplayer/tokenresolver.py, resources/lib/vrtplayer/tvguide.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py, resources/settings.xml, test/vrtplayertests.py
- A predefined set of log_levels: Quiet, Info, Verbose, Debug
- Default log_level is 'Info'
- Log all HTTP requests as Verbose
- Log all invocations as Verbose
This is only the first step of a set of troubleshooting improvements.
=> Add new logging infrastructure

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/streamservice.py
Fix for https://github.com/pietje666/plugin.video.vrt.nu/issues/172
=> implemented max bandwidth for hls streams

resources/lib/vrtplayer/streamservice.py
I discovered that as soon as a query-string is added to a (live) stream_url, a 720p stream is part of the M3U8 file. This could be any string.
So this opens up the possibility to have 720p without the need for DRM.
=> Add 720p support without DRM

addon.py, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/vrtplayer/actions.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py
This implements an "* All seasons" feature like in stock Kodi.
It helps to navigate when seasons are not of interest to you.
To enable you need to set the "videolibrary.showallitems" setting
in Kodi at:
> Settings > Media > Video > Show "All items" entry
=> Add "* All seasons" feature like stock Kodi

resources/lib/vrtplayer/__init__.py, resources/lib/vrtplayer/streamservice.py, resources/lib/vrtplayer/vrtplayer.py
This adds Ketnet Junior live stream.
This fixes #207
=> Add Ketnet Junior

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiwrappers/kodiwrapper.py, resources/settings.xml
In some use-cases (e.g. when using favourites often) menu caching causes
new episodes to not appear when expected. In this case users can disable
this with an expected performance hit when navigating the menus.
This fixes #210 
This PR also changes the order of the Settings tabs to fix a long-standing issue related to the cursor being stuck in the email-field.
=> Add setting to disabe menu caching

.travis.yml, Makefile, addon.xml, requirements.txt, test/apihelpertests.py, test/streamservicetests.py, test/vrtplayertests.py
- Add unit tests to pylint
- Fix unit tests (even if they don't work as-is yet)
- Run streamserviceests.py as part of unit tests (not by Travis)
=> Fix unit tests

Makefile, addon.py, pylintrc, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/actions.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py, test/apihelpertests.py, test/searchtests.py
In the future I like to extend this implementation:
- Show TV show listing, and if you click through, show the programs that matched the search query.
- Sort by score
- Store previous search queries
=> Add search functionality

resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/streamservice.py, resources/lib/vrtplayer/tokenresolver.py, resources/lib/vrtplayer/tvguide.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py
- Rename 'open_path' and 'delete_path' into 'open_file' and 'delete_file'
- Use 'open_file' as contextmanager in our code
- Unquote URL's in log entries
- Rename 'content_type' into 'content'
This is split off #213
=> Various small fixes

resources/lib/vrtplayer/vrtplayer.py
This fixes the categories scraper.
The VRT NU website has changed again, and as a result our unit-tests failed.
The v1.9.0 release already has fallback code, so is not affected.
=> Fix categories scraper

.travis.yml, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py, test/apihelpertests.py, test/searchtests.py, test/vrtplayertests.py
This PR adds 'content' support from backend to frontend.
This is split off from #213
=> Ensure season and episode listings use correct view

resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/tvguide.py, resources/lib/vrtplayer/vrtapihelper.py
Since most platforms running Kodi are of the Just Enough OS type,
they do not ship locale information for anything other than English.
And since Kodi does not have any supporting infrastructure, we have to
do this ourselves.
This fixes #184
=> Localize date format strings

.gitignore, test/__init__.py, test/credentials.json
And we ignore this file so it cannot be accidentally committed.
=> Get credentials from credentials.json

Makefile, addon.py, addon.xml, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/helperobjects/helperobjects.py, resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/actions.py, resources/lib/vrtplayer/favorites.py, resources/lib/vrtplayer/statichelper.py, resources/lib/vrtplayer/tokenresolver.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py, resources/settings.xml, test/favoritestests.py
This PR adds a way of tracking the programs you follow.
- Add a context menu to programs or episodes with either "Follow" or "Unfollow"
- Download and cache favorites from VRT NU
- Add an A-Z listing of followed programs
- Add a Recent listing of followed programs
- Add invisible setting 'usefavorites' to disable "My programs" (for unit tests)
- Disable brand filter in "My programs" recent listing (should be configurable really)
This fixes #181
=> Add "My programs" menu

addon.py, resources/lib/helperobjects/helperobjects.py, resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/favorites.py, resources/lib/vrtplayer/streamservice.py, resources/lib/vrtplayer/tokenresolver.py, resources/lib/vrtplayer/tvguide.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py, service.py
We have overly long constructions like:
self._kodiwrapper.get_localized_string()
and this would now become:
self._kodi.localize()
=> Make code more readable

addon.py, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/helperobjects/helperobjects.py, resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/favorites.py, resources/lib/vrtplayer/streamservice.py, resources/lib/vrtplayer/tokenresolver.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py, resources/settings.xml, service.py, test/apihelpertests.py, test/searchtests.py, test/streamservicetests.py, test/vrtplayertests.py
- Re-added the settings option to enable/disable favorites
- Only enable My programs when settings enable it and credentials are detected
- Reorganize unit tests (move from vrtplayer to apihelper)
This is done over concerns from https://github.com/pietje666/plugin.video.vrt.nu/pull/213#issuecomment-492657267
Additionally, I think we need to add help to individual settings to give a little bit more insight into how settings affect the VRT NU addon. This also gives more maturity to our addon settings pages...
=> Re-add option to disable favorites

resources/lib/vrtplayer/tvguide.py, resources/lib/vrtplayer/vrtplayer.py, test/tvguidetests.py
This adds the previous, current and upcoming live show to the live
stream plot.
This also includes a fix where we would show today's TV-Guide, while the
EPG information goes from 6AM until 6AM. So before 6AM we would show the
previous day's EPG.
=> Add TV-Guide information to live stream plot

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/vrtplayer/tvguide.py, test/apihelpertests.py
Because we did not make a distinction between the actual time and the
EPG data we needed to fetch, the EPG information would be off.
=> Fix Live TV EPG after midnight

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/vrtplayer/statichelper.py, resources/lib/vrtplayer/tvguide.py, resources/lib/vrtplayer/vrtapihelper.py, test/tvguidetests.py
- Support for &ul; and &lt;li&gt;
- Use "My most recent" and "Mijn meest recent
- Highlight TV show name in recent listings
- Translations for 'Now' and 'Next'
=> Various fixes

resources/lib/kodiwrappers/kodiwrapper.py
As reported, setIsFolder is new in Kodi 18, and we also support Kodi 17.
Thanks @mediaminister
=> Disable setIsFolder use (Kodi 18 specific)

README.md, addon.py, addon.xml, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/__init__.py, resources/lib/vrtplayer/favorites.py, resources/lib/vrtplayer/vrtapihelper.py, resources/settings.xml, test/apihelpertests.py
This PR enables the (re-)installation of Widevine for testing purposes.
=> Add 'Install Widevine' settings option

addon.py, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/__init__.py, resources/lib/vrtplayer/favorites.py, resources/lib/vrtplayer/streamservice.py, resources/lib/vrtplayer/tokenresolver.py, resources/lib/vrtplayer/tvguide.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py, resources/settings.xml, test/vrtplayertests.py, test/xbmcaddon.py
- Caching and fallback framework for listings (e.g. A-Z, or categories)
- New troubleshooting option to invalidate caches
This fixes #241
=> Implement caching framework

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/vrtplayer/tvguide.py, resources/lib/vrtplayer/vrtapihelper.py, resources/lib/vrtplayer/vrtplayer.py, resources/settings.xml
This is purely for testing performance difference and to save on
bandwidth/cycles on older hardware.
=> Add option to enable/disable fanart

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiwrappers/kodiwrapper.py, resources/lib/vrtplayer/vrtapihelper.py, resources/settings.xml, service.py, test/xbmcaddon.py
- Replace a fixed channel filter by a dynamic filter
- Add a Channels settings tab for configuring the filter
This fixes #242
=> Add a channel filter for Most recent and Soon offline

resources/lib/vrtplayer/tvguide.py
This fixes an issues where today, tomorrow and yesterday would not bring you to the advertised date between 12AM and 6AM.
=> Fix recalculation when using today, tomorrow, yesterday

Makefile, resources/lib/vrtplayer/tvguide.py
Since we know there is no transmission if we can't find a match or a next program when we reach the end. We do know when the previous program ended, and we know the next broadcasting day starts at 06:00. So let's add this for completeness.
The vrtnu website is doing the same thing.
=> Add timing to 'No transmission'

resources/lib/favorites.py
The `usefavorites` setting doesn't work properly. When the setting is disabled, it is still calling the `get_favorites` function that blocks the menus when the user has no credentials provided.
This is a quick fix that solves the menu blocking.
=> quick fix: only get favorites when activated

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po
A few strings were not correct between en_gb and nl_nl, which caused the
translation not to work.
=> Fix translation strings

addon.xml, pylintrc, resources/lib/helperobjects.py, resources/lib/vrtapihelper.py, resources/lib/vrtplayer.py, test/apihelpertests.py, test/favoritestests.py, test/routertests.py, test/searchtests.py, test/streamservicetests.py, test/tvguidetests.py, test/vrtplayertests.py, test/xbmc.py, test/xbmcaddon.py, test/xbmcgui.py, test/xbmcplugin.py, test/xbmcvfs.py
- Adding docstrings to all remaining modules, except unit tests
- Remove unwanted context snipper from addon.xml (testing leftover)
- Re-add pylint missing-docstring test
The helper-objects may need a more sensible docstring.
Other docstrings probably could use some more context information as well.
=> Add docstrings to remaining modules

resources/lib/kodiwrapper.py, resources/lib/streamservice.py, resources/lib/tvguide.py, resources/lib/vrtapihelper.py, resources/lib/vrtplayer.py, test/xbmcaddon.py
The xbmcaddon getSetting() function returns an empty string for non-existing settings. Which makes it unclear if a setting is missing, or simply set to an empty string on purpose.
But for boolean values, this is not a real issue.
This implements providing a default in case the setting does not exist, or is empty.
- Default values for get_settings()
- Improve kodi xbmcaddon stub
- Fix pylint issues related to long lines
=> Add default values for missing settings

resources/lib/__init__.py, resources/lib/favorites.py, resources/lib/kodiwrapper.py, resources/lib/router.py, resources/lib/tvguide.py, resources/lib/vrtapihelper.py, service.py, test/apihelpertests.py, test/favoritestests.py, test/searchtests.py, test/streamservicetests.py, test/tvguidetests.py, test/vrtplayertests.py
The original implementation was very invasive and touched almost every
API to pass a parameter `use_cache` so the specific cache would be
invalidated.
This is easier but as effective.
This fixes #302
=> Add a Refresh context menu

Makefile, resources/lib/kodiwrapper.py, resources/lib/vrtapihelper.py, resources/lib/vrtplayer.py, test/streamservicetests.py, test/vrtplayertests.py
- A Live TV entry in the Channel's tvshow listing (as detailed in #313)
- Let `make zip`  create a zip without testing
- Leave `make` or `make all` to do everything
- Remove 2 pylint ignores
This fixes #313
=> Add a channel live tv entry in channel listing

resources/lib/__init__.py, resources/lib/favorites.py, resources/lib/helperobjects.py, resources/lib/kodiwrapper.py, resources/lib/router.py, resources/lib/statichelper.py, resources/lib/tvguide.py, resources/lib/vrtapihelper.py, resources/lib/vrtplayer.py, resources/settings.xml, service.py, test/apihelpertests.py, test/favoritestests.py, test/routertests.py, test/searchtests.py, test/streamservicetests.py, test/tvguidetests.py, test/vrtplayertests.py, test/xbmc.py, test/xbmcplugin.py
This implements the new router design as discussed in https://github.com/pietje666/plugin.video.vrt.nu/issues/103
=> Clean url router

addon.py, resources/lib/streamservice.py, resources/lib/vrtplayer.py, test/routingtests.py
- Adding docstrings to all routes
- Don't instantiate single-purpose objects
- Don't import libraries that are usd infequently in vrtplayer.py
- Remove test() function from addon.py for testing routing
=> More cleanups to new routing interface

resources/lib/__init__.py, resources/lib/vrtapihelper.py, resources/lib/vrtplayer.py
- Show the Movies category as movie titles, not subfolders
- Show the Kortfilm feature as movie titles, not subfolders
- Show real title for 'oneoff' programs, likes movies
- Remove boolean() call for use_favorites (no longer required)
This fixes #323
=> Show movies and shortmovies directly

addon.py, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiwrapper.py, resources/lib/vrtapihelper.py, resources/lib/vrtplayer.py, resources/settings.xml
This PR includes 2 new optional entries in My programs.
This relates to #133
=> Add My movies and My documentaries to My programs

addon.py, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/favorites.py, resources/lib/helperobjects.py, resources/lib/kodiwrapper.py, resources/lib/metadatacreator.py, resources/lib/tvguide.py, resources/lib/vrtapihelper.py, resources/lib/vrtplayer.py, test/apihelpertests.py, test/routingtests.py
- Simplify /cache/delete interface
- Delay import json
- Make is_playable=False default in TitleItem
- Add playcount=0 InfoLabel for live streams so they are not watched
- Renamed "My A-Z" to "My favourite programs"
- Move My movies and My documentaries to the end of "My programs" menu
- Ensure unit tests are not over 160 rows
- Renamed "video_dict" to "info_dict"
This fixes #326
=> Assorted fixes

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po
To avoid any confusion to when this option is required.
=> Improve Widevine/DRM settings text

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiwrapper.py, resources/lib/streamservice.py
- when a HLS AES stream fails instruct the user to enable DRM and Inputstream Adaptive based on the current settings.
=> improve stream error handling

resources/lib/helperobjects.py
So currently when you type in a username and password, you can visually
verify the username is correct, but the password is a bunch of
asterisks. So if the login failed we assume the username was correct
(and can be verified by the user) but since the password is not visible
and cannot be edited we reset only the password.
This is a bit more userfriendly. An option to show the password would be
even better so we don't need to reset anything (just mark as invalid).
=> Do not clear username if login failed

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/favorites.py, resources/lib/helperobjects.py, resources/lib/kodiwrapper.py, resources/lib/statichelper.py, resources/lib/streamservice.py, resources/lib/tvguide.py, resources/lib/vrtapihelper.py, resources/lib/vrtplayer.py, resources/settings.xml, test/vrtplayertests.py
This implements showing oneoff programs in the list of tvshows. This
adds the convenience of not requiring to dig one level deeper to get to
the video.
- Mixing multi-episode programs and one-off episodes (movies and documentaries)
- Add a one-off cache that is used for all oneoff-queries (number of oneoff programs is about 30)
- Indicate which programs are being followed using a °-character)
This fixes #329
=> Mix tvshows and oneoff episodes

resources/lib/statichelper.py, resources/lib/tvguide.py, resources/lib/vrtapihelper.py, test/vrtplayertests.py
This adds basic favorites support to the TV Guide. This is however only
possible for episodes that have already aired, because we need the
program name from the URL that is provided.
This fixes #336
=> Add favorites support to TV Guide

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiwrapper.py, resources/lib/streamservice.py, resources/lib/vrtapihelper.py, resources/settings.xml
- Hide (Widevine) DRM settings on Kodi versions that don't support (Widevine) DRM
- Improve stream error handling for HLS AES (just to be safe)
- Fixed some typos in strings.po
- Fixed some wrong msgctxt id's
- Workaround for urllib quote complaining about utf-8 on python 2: https://bugs.python.org/issue23885
=> improve streaming settings

addon.xml, resources/lib/kodiwrapper.py, resources/lib/tvguide.py, resources/lib/vrtapihelper.py, resources/lib/vrtplayer.py, test/apihelpertests.py
- Only order as unsorted when tvshows + oneoff
- Optional support for coloured studio icons
- Remove redundant 'icon' from setArt
- Order by episode when showEpisodeNumber is set
=> Only order 'unsorted' when tvshows + oneoff

.gitignore, addon.py, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiwrapper.py, resources/lib/search.py, resources/lib/tvguide.py, resources/lib/vrtapihelper.py, resources/lib/vrtplayer.py, test/routingtests.py, test/searchtests.py
- Moving all search-related stuff into search.py
- Add a search-menu with previous search queries
- Store search history into userdata/search_history.json
- Add entry to clear complete search history
This fixes #301.
=> Add basic search menu and store search queries

resources/lib/tvguide.py
I was convinced I fixed this yesterday, but I probably forgot to backport it to my tree.
=> Fix UTF8 issue with quote()

addon.py, resources/lib/favorites.py, resources/lib/kodiwrapper.py, resources/lib/statichelper.py, resources/lib/vrtapihelper.py, test/favoritestests.py, test/xbmc.py, test/xbmcaddon.py
This includes:
- always use unicode strings inside the add-on
- only decode/encode  when necessary for input and output on the outer edges of the add-on
- fixes problems with special characters, for instance follow/unfollow Terug naar Siberië
=> implement Unicode Sandwich

.gitignore, addon.py, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/tokenresolver.py, resources/settings.xml
Fixes #351 
This adds a function to `tokenresolver.py` to just check the tokens. I couldn't reuse an existing function since they look in cache first. The credentials tab in the settings has an action now to run this function that checks the login credentials. A message is displayed indicating success or failure, and the settings dialog is shown again.
Note that I had to add `option="close"` to the settings since Kodi only saves the settings when the dialog is closed.
I also added `*.pyo` to the `.gitignore` file. Kodi creates these compiled files.
=> Add an action to check your credentials from the add-on settings.

resources/lib/statichelper.py, test/run.py
Also fixed an issue with converting page number.
Use it like this:
- `./test/run.py plugin://plugin.video.vrt.nu/recent/1`
- `./test/run.py /favorites/recent`
=> Add a run command for CLI testing/debugging

resources/lib/__init__.py, test/test_apihelper.py
It appears the Radio 1 live TV stream is behind **vualto_events3_geo**
This fixes #359
=> Add Radio 1 live TV stream

resources/lib/kodiwrapper.py
This happened for me when pressing back at the wrong time.
I have seen other cases where pressing back resulted in exiting the addon and ending up in some generic video Kodi menu. It's always related to unfortunate timing and I never can reproduce it if I try.
This case was different because there was an actual Exception and error-notification.
=> Handle a TypeError when download gets interrupted

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/favorites.py, resources/lib/kodiwrapper.py, resources/lib/search.py, resources/lib/streamservice.py, resources/lib/tvguide.py, resources/lib/vrtapihelper.py, resources/lib/vrtplayer.py, test/test_kodi.py
By integrating string formattig with the localize() function call we can
make both the translations easier to comprehend, as well as the code
more transparant/readable.
And by using SafeDict() it is also more reliable if arguments do not add up.
When a key is not found the 'template' remains in the string.
=> Integrate pyformat with localize()

addon.py, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/search.py, resources/lib/vrtapihelper.py, test/test_routing.py
- A new context menu item to remove a keyword from search history
- A new API call to add a keyword to the search history
- A new API call to remove a keyword from the search history
- Clean up existing context_menu sections
- Integration tests added
This fixes #389
=> Add search context menu and API calls

addon.xml
This fixes an issue where the add-on is not visible in Chorus2 Web Interface and Embruary skin widget selection window.
=> fix extension point order

resources/lib/streamservice.py, test/test_routing.py
VRT NU html has changed and this broke the webscraper that is used by the tv guide.
- fix for broken webscraper
- quick fix for airdate unit test
=> fix broken streamservice webscraper

resources/lib/tokenresolver.py
After removing the password clearing functionality, we got an endless OK dialog/settings dialog loop when the user tries to start a VOD stream and can't provide good credentials.
With this pull request the user can exit the loop if he doesn't change the bad credentials.
=> quit bad credentials loop if user doesn't want to change credentials

Build-Zip.ps1, resources/lib/addon.py, resources/lib/apihelper.py, resources/lib/kodiwrapper.py, resources/lib/metadata.py, resources/lib/search.py, resources/lib/tvguide.py, resources/lib/vrtplayer.py, test/test_kodi.py, test/test_routing.py
- Use the new high-res fanart instead of low-res icons
- Exclude .pyo files in Build-Zip
- Small changes to /tvguide rating
- Remove (debug) prints from test_kodi localize() tests
=> Use new high-res fanart by default

resources/lib/kodiwrapper.py, resources/lib/tokenresolver.py
In an attempt to fix the root cause of https://github.com/pietje666/plugin.video.vrt.nu/issues/411 I implemented unicode support for VRT NU passwords and email addresses.
Successfully tested on:
- Windows 10 x64 Kodi 19 python3
- Windows 10 x64 Kodi 18.3 python2
- LibreELEC 8.2.5 Kodi 17.6
- Linux x64 Kodi 18.3 python2
=> support special chars in credentials

resources/lib/kodiwrapper.py
This is visually more appealing.
=> Ensure breadcrumbs always include 'VRT NU'

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/settings.xml
- Add InputStream Helper to troubleshooting settings
- Rename "No transmission" to "Retransmissions" (impacts Eén and Canvas)
=> Add InputStream Helper to Troubleshooting settings

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/addon.py, resources/lib/vrtplayer.py
Since the VRT NU app now also list "Favorieten" we want to make our
naming consisent to the VRT NU app.
=> Rename 'My programs' to 'My favorites'

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/addon.py, resources/lib/kodiwrapper.py, resources/settings.xml
Since inputstreamhelper will now be used for manual (re)installation of
Widevine, the existing reference to the inputstreamhelper settings is
sufficient for users to Troubleshoot their Widevine setup.
=> Remove Widevine installation (API and settings)

.gitignore, .travis.yml, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/metadata.py
- Simply show the number of hours/days/months/years available
- Show it before showing **Geo-blocked**
- Ignore the add-on checker logs
- Remove unneeded Travis CODECOV_TOKEN
=> Simplify the availability of videos

test/test_streamservice.py
We need to exclude a few of the tests on Travis.
It seems that the main problem is that the secret credentials are only exported for commits to the master branch, not for user pull requests.
=> Try to fix the tests on Travis

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/apihelper.py, test/test_apihelper.py, test/test_favorites.py
One little step forward in trying to fix https://github.com/pietje666/plugin.video.vrt.nu/issues/399
- remove urlencode to support longer api urls
- provide user a message when api url is too long
- add unit tests to easily follow/unfollow hundreds of programs
=> provide user a message when api url is too long

addon.xml, resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/addon.py, resources/lib/favorites.py, resources/lib/kodiwrapper.py, resources/lib/metadata.py, test/routing.py
This fixes an annoying issue where your cursor would jump to the start of
the list when you unfollow a program in the favorite listing, and so the
selected ListItem disappears from under the cursor.
This also implements a smarter way to know where we are within the
add-on at any time.
This requires tamland/kodi-plugin-routing#20
=> Move cursor down when ListItem is unfollowed/removed

test/xbmcextra.py
Because of changes to the addon_settings (supporting more than one add-on) the credentials no longer worked as before.
=> This fixes the credentials when testing

Makefile
For compatibility with all shells, we shouldn't use brace expansion in Makefile
=> remove brace expansion from makefile

resources/lib/apihelper.py, test/userdata/addon_settings.json, test/userdata/search_history.json, test/xbmc.py, test/xbmcaddon.py, test/xbmcextra.py
We are now using `ADDON_USERNAME` and `ADDON_PASSWORD` for environment
variables and no longer write settings changes.
This used to be necessary for command line testing, but we now having
routing tests and settings survive tests.
This PR also includes suggestions from the addon checker.
=> Improve testing using Travis credentials

resources/lib/metadata.py
Showing banner art makes the information pane for seasons/episodes more
complete. And it allows the user to look at the art in close-up.
Only for one-offs the information pane shows 2 times the same image.
(because the Program art is the same as the Episode art)
But that's a trade-off.
VTM GO is doing this as well.
=> Add banner art for information pane

resources/lib/kodiwrapper.py
Fix an issue that causes logging as LOGNOTICE by default.
=> Filter based on max_log_level correctly

.travis.yml, Makefile, requirements.txt, test/test_proxy.py, test/userdata/search_history.json
This is a backport of the proxy-support tests from inputstreamhelper.
=> Add proxy-support testing

requirements.txt
The just released 1.0.0 no longer supports Python 2.7.
=> Fixed proxy.py version for Python 2.7

resources/lib/apihelper.py, resources/lib/metadata.py
Not sure why we are using targetUrl in the suggest API while we have a
programUrl (that does not have .relevant).
There probably is a good reason, but at least this gives the opportunity
to discuss it :-)
=> Use programUrl instead of targetUrl

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiwrapper.py, resources/lib/metadata.py, resources/lib/tokenresolver.py, resources/settings.xml, test/userdata/global_settings.json, test/xbmc.py
- Rename menu items in 'My favorites' menu
- Add My breadcrumbs support
- Add 'Go to program' context menu in 'Watch Later' and 'Continue watching' listings
- Change order of context items (Follow, Watch Later, Go to program, Refresh)
- Enable debug logging in global_settings.json
- Change log levels for Verbose and Debug
- Change default log level to Quiet
- Do not set resumetime in the first and last 60 seconds
- Show debug messages in (dark) gray
=> Rename My favorites menu items

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/addon.py, resources/lib/apihelper.py, resources/lib/favorites.py, resources/lib/kodiwrapper.py, resources/lib/metadata.py, resources/lib/playerinfo.py, resources/lib/resumepoints.py, resources/lib/search.py, resources/lib/service.py, resources/lib/statichelper.py, resources/lib/tokenresolver.py, resources/lib/tvguide.py, resources/lib/vrtplayer.py, resources/settings.xml, test/test_resumepoints.py, test/test_routing.py, test/test_tokenresolver.py, test/userdata/addon_settings.json
- Translation fixes wrt. context menu
- Fix breadcrumbs for Watch later and Continue watching
- Add routing integration tests for Watch later and Continue watching
- Fix issue during testing when resumepoints is not enabled
- Add a 'Refresh watching activity' to Expert settings menu
- Simplify Favorites/ResumePoints interface
- Use total-value from resumepoints for metadata resumetime
- Fix issue causing empty 'Continue watching' listing
- Fix issue with caching of Watch later and Continue watching listings
=> Various resumepoint fixes

resources/lib/metadata.py, test/xbmcplugin.py
Since the TV EPG schedule has now additional information we can take
this into account to follow a program, go to a program or watch an
episode later.
This PR also includes:
- Fix a bug where some EPG information was blank if it did not have a vrt.whatson-id
- Remove channel from EPG plot (since it is now in the breadcrumbs)
This fixes #524
=> Improve TV guide with new metadata

resources/lib/apihelper.py
This fixes an issue with listing seasons that contain spaces in `seasonTitle`.
For instance: 2019 najaar, 1 compilatie, 2019 NJ, 2 compilatie
We only encode spaces to keep api urls as short as possible.
=> support api urls with spaces

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/metadata.py
There was no availability information if there was less than one hour to
go.
=> Fix last hour for offline content

resources/lib/apihelper.py
This also adds the now-playing string to the channel-centric livetv
entry. Since this also uses a live screenshot as fanart this fits the
intended use-case.
=> Also add now-playing to channel-centric listing

resources/lib/service.py
This is to avoid instantiating KodiWrapper for all events.
=> Only instantiate KodiWrapper when needed

resources/lib/streamservice.py, resources/lib/vrtplayer.py
I got another HTTP Error 415: Unsupported Media Type, although we do not
report or log this error anywhere.
This change adds it to the dialog and logs it to the log. So that if it
gets reported (e.g. to VRT NU), hopefully the details will help.
PS I got this error with the HLS stream of episode 5 (season 4) of 24 hours in police custody. I reported this to VRT NU.
- Put the HTTP Error in the dialog
- Log the HTTP Error to a log file
- Don't handle resumepoints if stream is None (and not played)
=> Add HTTP error to dialog

test/test_proxy.py, test/xbmcvfs.py
Since the proxy implementation on Python 2 is less reliable, we trust
the results of the tests on Python 3.
=> Skip proxy test on Python 2

resources/lib/metadata.py
Only fill in properties when using VRT NU resumepoints because setting resumetime/totaltime breaks standard Kodi watch status.
=> Only fill in prop_dict when using VRT NU resumepoints

resources/lib/tokenresolver.py
This prevents that we end up with empty token files, related to this bug: https://github.com/pietje666/plugin.video.vrt.nu/issues/554
=> Make sure we don't write empty tokens to cache

resources/lib/apihelper.py, resources/lib/metadata.py
Re-evaluating the context menu, I think it makes more sense to put
'Watch later' first. The rationale is that for individual video's or
episodes this it more related to the context (episode) then
program-related context menu items.
For a program, there is no 'Watch later' item, so it starts with
'Follow program' and 'Go to program'.
And only then we have 'Refresh menu' which is not related to the context
at all.
So the order is: **Episode** > **Program** > **Menu**
=> Change the order of context menu items

resources/lib/apihelper.py, resources/lib/data.py, resources/lib/metadata.py, resources/lib/resumepoints.py
This ensures the same margin is being used for both resumepoints and
upnext so that when moving to the next epside, the current episode is
considered watched.
=> Use same margin for resumepoints and upnext

resources/lib/playerinfo.py
This is to ensure forwarding to the end marks a video as watched.
This fixes #564
=> Store the totaltime when playback has ended

resources/lib/apihelper.py, resources/lib/kodiwrapper.py, resources/lib/metadata.py, resources/lib/tvguide.py, resources/lib/vrtplayer.py
This PR doesn't store settings once on activation, but reevalutes
settings on use. I don't know what the performance impact is, but since
it is backed by C++ I would expect this to be efficient :-)
=> Making settings instantaneous

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/apihelper.py, resources/lib/data.py, resources/lib/kodiwrapper.py, resources/lib/metadata.py, resources/lib/search.py, test/test_vrtplayer.py
In order to add new categories, I had to renumber some existing entries.
It is weird that VRT NU now also added a "Gloednieuw" section, where there already was a "Nieuw" section.
I also think we have to improve how we support "featured" content. We should add this information to the plot (lacking an alternative). And maybe add a context menu to go to the featured sub-menu to find similar featured content.
=> Add new featured categories

resources/lib/kodiwrapper.py, resources/lib/service.py
This should preserve the path history, so you can return to the previous container when navigating after playing a video.
=> Use Container.Update instead of Container.Refresh

resources/lib/addon.py, resources/lib/apihelper.py, resources/lib/service.py, resources/lib/statichelper.py, resources/lib/vrtplayer.py, test/test_routing.py, test/test_statichelper.py, test/test_vrtplayer.py
While testing I found out `whatson_id` is not unique. Some episodes have multiple versions on VRT NU, versions with or without audio description or Flemish Sign Language.
It turns out these versions have the same `whatson_id`. 
For instance: Dag Sinterklaas: https://vrtnu-api.vrt.be/search?i=video&facets[whatsonId]=762744552527
This causes Up Next to play a next episode with audio description while previous episodes were played without audio description.
=> Use video_id for Up Next because whatson_id is not unique

resources/lib/service.py
Apparently Python 3.5 may be common using Debian Stretch (OSMC).
=> This fixes a known issue on Python 3.5

.gitignore, Makefile, resources/lib/kodiutils.py, test/read_profiling_stats.py, test/xbmc.py
- A global ADDON instance to be used by all kodi functions
- A profiling framework in Make and a script to read profiling data
- Reduce some complexity added to avoid instantiating Addon()
- Various additional fixes to improve performance on ListItems
- Fix a performance regression in xbmcaddon stub
The profiling framework may help in the future to find performance regressions.
You can simply do
$ make profile path=/favorites/recent
To get profile_stats written down to your project directory with branch and commit hash included.
You can do this for different branches to get multiple stats.
Then you can read out this data using:
$ ./test/read_profiling_stats.py <profile_stats.bin>
And you can start comparing the output from different branches.
This fixes #604
=> Fix performance regression and add profiling framework

resources/lib/addon.py, resources/lib/addon_entry.py, resources/lib/kodiutils.py
This is the easiest solution for ensuring we have up-to-date settings.
But it incurs a small performance hit on every invocation.
This fixes #560
=> Renew ADDON on every invocation

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/apihelper.py, resources/lib/favorites.py, resources/lib/kodiutils.py, resources/lib/search.py, resources/lib/tvguide.py, resources/lib/vrtplayer.py, resources/settings.xml, test/userdata/addon_settings.json
This makes the HTTP cache ttl configurable rather than hard-coded.
We implemented a 'direct' cache ttl (5min) and an 'indirect' cache
ttl (60min)based on the relation the cache has to the listing that
requires it.
This fixes #541
=> Make HTTP cache ttl configurable

resources/lib/kodiutils.py, resources/lib/playerinfo.py, resources/lib/service.py
- Catch exception when getting position or totaltime
- Push upnext in thread
- A new container_reload() which only reloads the original menu
- Change conditions of when container needs to be reloaded (disable it seems to work)
- Quit player when we seek to the end (this was broken by something?)
This includes the safer/saner bits from #567
=> More PlayerInfo improvements

resources/lib/playerinfo.py
VRT NU Search Api sometimes contains an empty `whatsonId` and sending an empty `whatsonId` to VRT Nu Resumepoints Api results in a "bad" resumepoint.
This pull request fixes this bug.
=> Support empty whatsonIds

resources/lib/apihelper.py, resources/lib/playerinfo.py, resources/lib/service.py, test/xbmc.py
Sometimes an "Up Next" episode fails to play because the previous episode caused an `onPlayBackEnded` event while the next episode is still setting up. I experienced this while watching Peulengaleis episodes.
This pull request fixes this problem.
=> Seamlessly play Up Next episodes

resources/lib/playerinfo.py, resources/lib/service.py
Migrate to using a base64-encoded payload for Up Next communication.
This requires Up Next v1.0.5 or newer
=> Support base64 payload for Up Next communication

resources/lib/kodiutils.py, resources/lib/playerinfo.py
This pull request fixes an issue where the current directory listing is not updated after finishing a "Watch later" episode.
As Kodi uses different resumepoint margins than VRT NU and Kodi has no API to read these variables, I hardcoded the standard Kodi margins to force a container reload when needed.
You can find more information about the Kodi resumepoints margins at https://kodi.wiki/view/HOW-TO:Modify_automatic_watch_and_resume_points
=> Update 'Watch later' after watching episode

resources/lib/kodiutils.py
While testing I experienced that passing a file handle from `xbmcvfs` to `json` module doesn't work very reliable. Sometimes it fails to read the file properly which causes a `ValueError` on Python2 or a `JSONDecodeError` on Python3.
When testing the json file manually, there is never a problem, it's always valid json.
Directly passing unicode to the `json` module seems to fix these errors.
=> Use unicode with json module

resources/lib/favorites.py, resources/lib/resumepoints.py, test/test_resumepoints.py
Something that bothered me for some time is that the internal representation was called _favorites or _resumepoints and this is confusing as local instances would also be called _favorites or _resumepoints. Renaming it to _data.
=> Rename internal representation _data

resources/lib/playerinfo.py
It makes no sense to push 'Up Next' when a user early exits Kodi Player.
=> Only push 'Up Next' when Kodi Player is playing

resources/lib/kodiutils.py
Due to a logic error the ListItem fanart was always replaced with the add-on fanart. This fixes it.
=> Fix missing ListItem fanart

resources/lib/playerinfo.py, test/test_resumepoints.py
There were several mistakes in the logic to determine if the container should be updated manually. I rewrote it to reduce container updates even more.
=> Reduce manual container updates to absolute minimum

resources/settings.xml
If you don't close the settings, the newly installed add-on does not
trigger an update of the settings. So we need to close it and hope the
user returns to see the settings have changed.
=> Close settings when installing an add-on

resources/lib/kodiutils.py, test/test_kodiutils.py, test/xbmc.py
This extends the existing interface to support more than one command.
So you can now do any of the below:
```python
jsonrpc(method='Input.Down')  # Use kwargs (as used now)
jsonrpc(dict(method='Input.Down'))  # Use dict as arg
jsonrpc(dict(method='Input.Down'), dict(method='Input.Up'))  # Use dicts as args
```
=> Extend jsonrpc() to support list of commands

resources/lib/kodiutils.py, resources/lib/playerinfo.py
This fixes a bug where watch status was not updated when a user has non-integer values configured for `ignoresecondsatstart` and `ignorepercentatend` in advancedsettings.xml
=> Get advanced settings as an integer

resources/lib/playerinfo.py
Another Kodi bug that came to surface, Kodi Player sometimes returns a total time of 0.0 and this causes unwanted behaviour with VRT NU Resumepoints API.
We should ignore this zero value and pass the previous value or the initial `None` value to VRT NU Resumepoints API.
=> Don't update total to 0.0

resources/lib/playerinfo.py, resources/lib/resumepoints.py, test/test_resumepoints.py, test/test_routing.py
- Avoid setting resumepoints for livestreams
- Avoid updating resumepoints with data from previous episode
- Avoid sending zero position values because this triggers unwanted resumepoint deletion
- Move local resumepoint cache updates to separate functions
- Use `update_online` json response to update local cache
- Make sure unit tests don't remove existing watchLater episodes or permanently add new watchLater episodes
=> Assorted resumepoint fixes

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiutils.py, resources/lib/playerinfo.py, resources/lib/resumepoints.py, resources/lib/service.py, resources/lib/vrtplayer.py, test/test_resumepoints.py
- Reorganize resumepoints.py
- Wait for the resumepoints to be updated before loading the menus
=> Improve resumepoints

resources/lib/playerinfo.py
I introduced this regression in https://github.com/pietje666/plugin.video.vrt.nu/commit/534687ef29268e352ec65887ba35bcfd78ca960f
This reverts this change to the previously working code, I tested this again on Kodi 17  and 18 and it works.
=> Only listen to vrt nu add-on urls

resources/lib/apihelper.py, resources/lib/metadata.py, resources/lib/playerinfo.py, resources/lib/streamservice.py, resources/lib/tvguide.py, resources/lib/utils.py, resources/lib/webscraper.py, test/test_streamservice.py, test/test_vrtplayer.py, test/test_webscraper.py
This pull request fixes watching activity for programs that don't have an `assetPath` key in VRT NU Search API:
- eva-ontmoet
- een-italiaanse-reis
- vrt-nws-extra
- van-a-tot-z--luc-tuymans
- klimaatbetoog
- de-stad-van-morgen
- van-a-tot-z--piet-hoebeke
- het-koninkrijk-van-rene-heyvaert
- lang-zullen-we-lezen
- van-a-tot-z-johan-braeckman
- van-a-tot-z--edel-maex
- marathonradio
- girls-talk
- van-a-tot-z--connie-palmen
- van-a-tot-z--dirk-de-wachter
- van-a-tot-z
- 22-3-1-jaar-later---het-onderzoek
- live-op-kies19
- Move web scraping functionality to separate file
- Improve getting an `asset_id` using web scraping
- Fix for getting a short episode url from VRT Schedule API
- Fix for getting fresh resumepoints when (re)loading TV guide menus
This possibly …
=> Fallback to web scraping for watching activity

resources/lib/data.py, resources/lib/webscraper.py, test/test_webscraper.py
VRT removed the live stream player from the channel pages of Eén and Canvas (https://www.vrt.be/vrtnu/kanalen/een/ https://www.vrt.be/vrtnu/kanalen/canvas/) and this broke web scraping live stream attributes for Eén and Canvas.
This pull request fixes this.
This was not really a problem for existing add-on functionality, because the add-on relies on `live_stream_id` in `data.py`, but it's good to keep web scraping up to date as a fallback.
=> Fix livestreams

resources/lib/apihelper.py, resources/lib/helperobjects.py, resources/lib/kodiutils.py, resources/lib/metadata.py, resources/lib/search.py, resources/lib/tvguide.py, resources/lib/vrtplayer.py, test/test_apihelper.py, test/test_tvguide.py, test/test_vrtplayer.py
- Clear distinction between Label and Title
- Add `get_title()` metadata function
- Add `get_mediatype()` metadata function
- Set proper mediatype for oneoff videos
- Add FIXMEs for a known label/title issue in Kodi/Estuary
=> Differentiate between Label and Title

resources/lib/playerinfo.py, resources/lib/resumepoints.py
Normally, VRT NU resumepoints are deleted when an episode is (un)watched and Kodi GUI automatically sets the (un)watched status when Kodi Player exits.
This mechanism doesn't work with "Up Next" episodes because these episodes are not initiated from a ListItem in Kodi GUI. Preserving the VRT NU resumepoints for "Up Next" makes sure the watched status can be forced in Kodi GUI using the playcount infolabel.
This pull request fixes https://github.com/pietje666/plugin.video.vrt.nu/issues/661
=> Always preserve Up Next resumepoints

resources/lib/webscraper.py, test/test_webscraper.py
The previous check `if not categories` didn't detect when `name` or `id` was empty and this implies that in some cases the fallback to the internal hard-coded categories doesn't work in v2.3.1 and earlier.
When the cache expires all users will get a blanco categories listing, all new users got already a blanco categories listing when opening the categories menu:
We need a 2.3.2 release as soon as possible.
=> Check if categories contain all necessary info

resources/lib/tvguide.py, test/test_tvguide.py, test/xbmcextra.py
Apparently the range for the EPG has changed a bit.
The downside of this is that **Today** is not longer visible from the listing. I would prefer a better view for this.
=> Improve tv guide range: 3 weeks past, 2 weeks future

test/test_apihelper.py, test/test_webscraper.py
This fixes two unit tests:
- VRT removed the Ketnet livestream from https://www.vrt.be/vrtnu/kanalen/ketnet/, so we shouldn't look for a livestream on this url anymore.
- VRT added a 2020 Pano season, so number of items to test for should be increased with 1.
=> Fix webscraper and apihelper tests

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/addon.py, resources/lib/vrtplayer.py, resources/settings.xml
Just like Movies and Docus, also Music has oneoff videos and docus that people may miss out on when staying inside the Favourites menu.
Unfortunately it includes a reordering of translations to keep it sane.
=> Add a favourites music subsection

resources/lib/apihelper.py
This will make oneoff programs more strict to avoid listing incorrectly tagged entries. We expect oneoffs to never have and episodeNumber that is not 0 or 1.
This fixes #670
=> Make oneoffs more strict

.github/workflows/ci.yml
This is to ensure that our required pipelines are not blocked because of
Codecov or Sonarcloud availability issues.
=> Allow coverage steps to fail

.gitattributes, .github/workflows/addon-check.yml, .github/workflows/ci.yml, .github/workflows/status.yml, Makefile, resources/lib/resumepoints.py, tests/test_settings.py, tests/test_tvguide.py
- Removal of local .coverage file
- Use upstream kodi-addon-checker
- Make sonarcloud checker more silent
- Add EPG testing
- Remove codecov checker
- Add ondemand tests without drm/ia
(Not yet sure this improves coverage, or even works from US)
=> Add better add-on tests

resources/lib/kodiutils.py, resources/lib/playerinfo.py, resources/lib/streamservice.py, resources/lib/vrtplayer.py, tests/xbmcgui.py
- ignore local version identifier when checking add-on version (for add-on versions that contain +matrix.1)
-  add compatibility with Kodi 19 Python API while preserving backwards compatibility with earlier Kodi versions: https://forum.kodi.tv/showthread.php?tid=344263&pid=2933596#pid2933596
=> Ensure codebase is compatible with Kodi 19

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/kodiutils.py
This adds support for another HTTP error 431.
Also includes a small translation fix.
This fixes #725
=> Handle HTTP 431 (Request header fields too large)

resources/lib/data.py
Now that vualto_events3 is no longer carrying the Radio 1 live stream we
have to use the faulty vualto_radio1 stream.
=> Reinstate original vualto_radio1

resources/lib/kodiutils.py
By the end of May,  both `inputstreamaddon` and `inputstreamclass` will be deprecated in the Kodi 19 nightly builds: https://forum.kodi.tv/showthread.php?tid=353560
This PR adds the new `inputstream` Python api for Kodi 19. For now, this is only needed for testing the add-on in Kodi 19.
=> Support new inputstream Python api in Kodi 19

.github/workflows/release.yml, Makefile
This automates a Github and Kodi repo release when pushing a tag matching the pattern v*:
For instance:
```
git tag v2.3.3
git push upstream v2.3.3
```
This pull request includes the following functionality:
- Creates a GitHub release with zip packages for Krypton/Leia and Matrix and adds the latest changelog from README.md as the body text.
- Submits pull requests to `xbmc/repo-plugins` for  Krypton/Leia and Matrix 
For this to work, you obviously need to create a release commit first where the addon version and news tag in `addon.xml `and the changelog in `README.md` is updated.
Furthermore two secrets need to be configured in https://github.com/add-ons/plugin.video.vrt.nu/settings/secrets
- **GH_TOKEN** A secret that contains a github token with at least a `public_repo`  OAuth scope. …
=> Automate release

resources/lib/kodiutils.py, resources/lib/streamservice.py
This is a workaround for https://github.com/add-ons/plugin.video.vrt.nu/issues/735
=> Always select HLS-stream for vualto_radio1

.github/workflows/release.yml
This should fix automatic creation of pull requests in `xbmc/repo-plugins` when tagging a new release: https://github.com/add-ons/plugin.video.vrt.nu/pull/733#issuecomment-622547001
=> Use GH_USERNAME secret for automatic submission

resources/lib/addon.py, resources/lib/kodiutils.py
This was always intended, but missing from the implementation. The
log_access() interface changes with this
=> Add query string to URI in log_access

resources/lib/data.py, resources/lib/iptvmanager.py
It is more convenient for our users if the more popular channels are
listed on top, regardless of the network. And if we can we should follow
known conventions.
| Channel       | Pref |Telenet | Belgacom
|--------------|------|----------|------------------
| Eén              | 1 | 2 | 1
| Canvas        | 2 | 4 | 2
| vtm             | 3 | 1 | 3
| Vier              | 4 | 3 | 4
| Vijf               | 5 | 6 | 5
| Zes              | 6 | 14 | 16
| Q2               | 7 | 5 | 6
| CAZ            | 8  | 9 | 8
| CAZ2          | 9  | ? | 18
| Vitaya         | 10 | 7 | 7
| Ketnet Jr    | 11 | N/A | N/A
| Ketnet        | 12 | 12 | 12
| VTM Kids   | 13 | 34 | 33
| BVN           | ? | N/A | N/A
| XITE           | ? | 44 | N/A
| Radio 1       | 901 | 900 | 800
| Radio 2 A    | 902 | 914 | 801
| Radio 2 L …
=> Add channel presets for IPTV Manager

resources/lib/metadata.py, resources/lib/utils.py
While testing Up Next, I found this little bug showing `&amp;` in the Kodi VideoPlayer.
=> Always unescape html in subtitle and shortDescription

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po
This is just to make sure that it is clear it is not yet supported as-is.
Even though it works fine and has no impact on the proper working of the
add-on whatsoever.
=> Mark IPTV Manager support as experimental

resources/lib/streamservice.py
Now that we fixed InputStream Adaptive to handle this more gracefully,
and the subtitle track has disappeared from the manifest, we can revert
our workaround.
This resolves #735
=> Revert vualto_radio1 workaround

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/favorites.py, resources/lib/resumepoints.py, resources/lib/streamservice.py, resources/lib/tokenresolver.py
This fixes roaming and updates some functions to be in line with the recent changes of the VRT NU website:
- add Apple to unsupported login warnings
- uniformize caching, refreshing and getting tokens
- cache additional tokens when getting a user X-VRT-Token
- support getting other tokens by name from cookiejar
- implemented updated api for getting a playertoken
- implemented updated api for getting a roaming token
I tested this on Windows, Linux and LibreELEC. Other systems should still be tested.
=> Rework tokenresolver

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/addon.py, resources/lib/kodiutils.py, resources/settings.xml
This offers an easier path for users to check for updates or re-install
the VRT NU add-on.
This relates to #765
=> Add a simple option for users to update VRT NU add-on

.github/workflows/status.yml, tests/checkvrtnu.py
In order to detect eventual breaking changes faster, it is useful to check if there is a new VRT NU app release and shortly fail the status checks to get an e-mail.
=> Add VRT NU app updates to status checks

resources/lib/tvguide.py
This is required to ensure "playing" a noop does not jump the cursor to
the first matching listitem.
=> Make noop calls unique

resources/lib/iptvmanager.py, resources/lib/tvguide.py
This PR improves the IPTV Manager integration by exposing the `subtitle`, and the `stream` URL.
The `stream` url can be used in Kodi Matrix to improve the direct playing of a program from the EPG guide, without using the airdate-api.
I would have loved to also add the `episode` number and the `genre` field, but it seems that these fields aren't available in the API we are using now (https://www.vrt.be/bin/epg/schedule.2020-06-06.json).
This information is available on the services.vrt.be API, so maybe it would make sense to start using that source? 
See http://services.vrt.be/htmlview/?href=%2Fepg%2Fschedules%2Ftoday%3Fchannel_code%3DO8%26type%3Dday&rel=http%3A%2F%2Fservices.vrt.be%2Fepg%2Frel%2Fschedule%2Ftoday
=> IPTV Manager improvements

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/apihelper.py, resources/lib/data.py, resources/lib/webscraper.py, tests/test_vrtplayer.py
VRT NU added "Levensbeschouwing" category, changed html  and changed the name of the "Kinderen" category.
The status check didn't detect these changes because the fallback to hardcoded categories was wrongly placed inside the webscraper function.
This pull request fixes this and adds all new changes to the hardcoded categories.
=> Fix categories

resources/lib/apihelper.py, resources/lib/iptvmanager.py
When start and end timestamps are provided, looking for the best matching "middle timestamp" to find an episode is more failsafe than just looking for the best matching start and end timestamps.
=> Improve airdate api

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/addon.py, resources/lib/apihelper.py, resources/lib/metadata.py, resources/lib/tvguide.py, resources/lib/vrtplayer.py, tests/test_routing.py
This includes improvements to play episodes from the VRT NU add-on TV guide and IPTV TV guide:
- play using whatson_id and add metadata to the play item (instead of VRT NU url webscraping)
- fallback to airdate 24-hour livestream cache if there is no VOD stream available
=> Improve playing from TV guide

resources/lib/apihelper.py, tests/test_apihelper.py, tests/test_vrtplayer.py
This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/783
It turned out that `seasons` is not a valid `xbmcplugin.setContent` type and this caused problems with the Arctic Horizon skin
=> Fix season items

resources/lib/kodiutils.py
Deleting tokens was broken since https://github.com/add-ons/plugin.video.vrt.nu/commit/3fbd36c3fe3a63cca73002ef7f042904ed2dc04f
This fixes this again.
=> Fix getting cache paths

resources/lib/vrtplayer.py
If there is no valid stream to play with Kodi Player, we should always return to the directory listing. Otherwise a busy dialog is shown forever.
=> Return to directory listing when stream is None

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/apihelper.py, resources/lib/favorites.py, resources/lib/kodiutils.py, resources/lib/resumepoints.py, resources/lib/streamservice.py, resources/lib/tokenresolver.py, resources/lib/tvguide.py, resources/lib/webscraper.py
Trying to provide error messages in Kodi GUI for all network problems improving https://github.com/add-ons/plugin.video.vrt.nu/pull/385
=> Show error messages when connections fail

resources/lib/streamservice.py, tests/test_streamservice.py
This PR adds some clarification about virtual subclip support in Unified Origin streaming platform. It also ensures that a past stop timestamp is always added to the stream url when a virtual subclip is needed because Unified Origin streaming platform fails to return a virtual subclip with a missing or future stop timestamp.
=> Fix stop timestamp in virtual subclip

resources/lib/apihelper.py
This fixes Up Next for Postbus X and Het Journaal:
- use `videoId` instead of `whatsonId` (fixes Postbus X)
- check if episodeNumber of next episode is different (fixes Het Journaal)
- use `programUrl `instead of `programWhatsonId`
- use `get_title` for the episode title instead of the `get_plotoutline`
=> Improve Up Next

tests/test_apihelper.py
VRT completed the metadata for Postbus X (https://vrtnu-api.vrt.be/search?facets[programName]=postbus-x) and this program can't no longer be used for the "without broadcastDate" test.
Wereldbeeld is now used to test episodes without broadcastDate.
=> Fix apihelper test for episodes without broadcastDate

resources/lib/streamservice.py
This fixes HD-quality for virtual subclip HLS streams as discussed in https://github.com/add-ons/plugin.video.vrt.nu/issues/802
=> Fix HD-quality for virtual subclip HLS streams

resources/lib/kodiutils.py
I experienced the following exception:
```
File "/storage/.kodi/addons/plugin.video.vrt.nu/resources/lib/kodiutils.py", line 1128, in open_url
log_error('{error}\nurl: {url}', error=exc.reason, url=url)
AttributeError: 'SSLError' object has no attribute 'reason'
```
What is strange is that this is on a Python 2.7.16 (LibreELEC v9.2.8)
while according to the documentation this should not be happening.
I implemented 2 workarounds, based on possible values for 2.7.8 and
earlier releases.
=> Fix exception on SSLError/log_error

resources/lib/tokenresolver.py
This is occuring in our automated testing (when VRT NU is having problems?).
This fixes the issue seen in: https://github.com/add-ons/plugin.video.vrt.nu/runs/1048178157
```log
======================================================================
ERROR: test_get_continue_episodes (test_resumepoints.TestResumePoints)
Test items, sort and order
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/runner/work/plugin.video.vrt.nu/plugin.video.vrt.nu/tests/test_resumepoints.py", line 46, in test_get_continue_episodes
self._resumepoints.update(
File "/home/runner/work/plugin.video.vrt.nu/plugin.video.vrt.nu/resources/lib/resumepoints.py", line 66, in update
self.refresh(ttl=5)
File …
```
=> Fix a known exception in TokenResolver

tests/checkvrtnu.py
VRT published a new VRT NU version on Google Play, but the script couldn't detect it within the hour. Increasing the detection time window to 90 minutes should solve this.
=> Increase time window for VRT NU version detection

resources/lib/tokenresolver.py, resources/lib/webscraper.py
This handles all none-responses from open_url().
I am not sure this is the best way to handle this, it is not very
elegant. Raising an exception helps in one case, but would not be
elegant in the other cases either.
=> Handle none-responses from open_url

.github/workflows/status.yml, resources/lib/apihelper.py, resources/lib/data.py, resources/lib/webscraper.py, tests/test_apihelper.py, tests/test_vrtplayer.py, tests/test_webscraper.py
While experimenting with **mitmproxy** I found out that the VRT NU Android app uses json files to display categories and channels.
This PR deprecates web scraping for the categories menu and uses https://www.vrt.be/vrtnu/categorieen/jcr:content/par/categories.model.json as a source instead.
=> Get categories from online json

resources/lib/playerinfo.py, resources/lib/streamservice.py, tests/test_streamservice.py
This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/281
This should be tested thoroughly during live broadcasts of "Het Journaal" (preferably 10 minutes after the live broadcast has started using the "Most recent" menu)
- 13:00 CEST: Het journaal 13u 
- 19:00 CEST: Het journaal 19u
- Sometime after 22:00 CEST: Het journaal Laat
This fix only works with InputStream Adaptive (when Widevine DRM is enablad in the add-on settings)
=> Fix unwanted virtual subclip behaviour

resources/lib/metadata.py, resources/lib/webscraper.py
This adds the kijkwijzer string to the mpaa Listitem infoLabel and adds PP and kijkwijzer string to the plot Listitem infoLabel.
This fixes #816
=> Add product placement and kijkwijzer metadata

.github/workflows/addon-check.yml, .github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/status.yml
Since we use the VRT NU workflows as a best practice, we might as well
document better what each of them is doing.
=> Document the different workflows

resources/lib/kodiutils.py, resources/lib/metadata.py
Rather than returning 'Not found' we return the untranslated string.
=> A better fix for a missing category

.github/workflows/ci.yml, tox.ini
This is a test to see if Python v3.9 support is ready in GitHub CI.
=> Prepare for Python v3.9

resources/lib/kodiutils.py
In Kodi 19 alpha 2 `xbmcvfs.translatePath` was added and this will replace `xbmc.translatePath` in future versions of Kodi.
=> Support xbmcvfs.translatePath

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/apihelper.py, resources/lib/data.py, resources/lib/kodiutils.py, resources/settings.xml
This fixes `EXCEPTION: Invalid setting type` in kodi.log in the following cases:
- when using `get_setting_float`.
- when using the labelenum setting type to select max_bandwith
- in most recent/soon offline menu
I guess `xbmcaddon.getSettingNumber` isn't functional because you can only define an integer type in the Kodi addon settings xml and in addition it is wrongly named as `type="number"`.
Maybe this can be fixed upstream if Team Kodi still accepts changes to the deprecated old settings format:
https://kodi.wiki/view/Add-on_settings#type.3D.22number.22
Relevant source code
https://github.com/xbmc/xbmc/blob/5230b683323ca58c62459a371c1306a6cb4d4644/xbmc/addons/settings/AddonSettings.cpp#L832-L844
`setting->GetType() `can never be a `SettingType::Number`, so it differs from …
=> Fix invalid setting type

.github/workflows/ci.yml, resources/lib/kodiutils.py
* Run CI on Windows (Python 2.7, Python 3.8 and Python 3.9)
* Fixes `datelong` formatting that currently is `%A, %e %B %Y`, but `%e` isn't a standard in Python. Under certain situations (like the setup of CI), this doesn't work.
=> Fixes a date parsing issue on windows and run CI

resources/lib/apihelper.py, resources/lib/metadata.py
This fixes an issue in Kodi 19 where an episode title is shown istead of the season.
This PR makes sure title and label is always the same for a season menu item.
=> Fix seasons menu in Kodi 19

resources/lib/kodiutils.py
This isn't the best way to do this, since it will redact every POST data that contains `password`, but since the data is already in a string format and url-encoded, this is the best I can do.
=> Don't log credentials in the Kodi debug log

resources/lib/kodiutils.py, resources/lib/playerinfo.py, resources/lib/streamservice.py
Play all streams using InputStream Adaptive from Kodi 18 onwards. This fixes https://github.com/add-ons/plugin.video.vrt.nu/issues/846
To test this, you need to disable "Use Widevine DRM".
=> Use InputStream Adaptive to play HLS

resources/lib/data.py, tests/test_apihelper.py
This is another brand, but does not have its own live stream.
Also add new bogus brand "throwback" to unit tests.
=> Add new Podium 19 channel

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/streamservice.py
This asks the user to toggle "Use Widevine DRM" when no compatible manifest url was found.
=> Ask user to toggle Widevine DRM setting when no compatible stream is found

resources/language/resource.language.en_gb/strings.po, resources/language/resource.language.nl_nl/strings.po, resources/lib/streamservice.py
This PR adds a clear error message for VRT NU age restricted content. When your VRT NU account doesn't contain a valid birth date, you can only play content that has no age restriction.
=> Add error message for age restricted content

resources/settings.xml
It seems VRT removed the HLS AES livestreams, this means you need Widevine CDM module to play livestreams. Setting Widevine DRM setting enabled by default makes sure the user can play livestreams without touching the settings.
=> Enable Widevine DRM by default

resources/lib/kodiutils.py
We have seen the following issue when using the VRT NU addon.
Unfortunately, after fixing this I could no longer reproduce the original read timeout to further troubleshoot my issues.
```
2022-02-15 22:24:23.669 T:1214  WARNING <general>: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/favorites
2022-02-15 22:24:23.766 T:1214  WARNING <general>: [plugin.video.vrt.nu] Got item from cache '/storage/.kodi/userdata/addon_data/plugin.video.vrt.nu/tokens/vrtloginat.tkn'
2022-02-15 22:24:23.771 T:1214  WARNING <general>: [plugin.video.vrt.nu] URL get: https://www.vrt.be/vrtnu-api/rest/lists/vrtnu-favoritePrograms?tileType=program-poster&tileContentType=program&tileOrientation=portrait&layout=slider&title=Mijn+favoriete+programma's
2022-02-15 22:24:29.097 T:1214    ERROR <general>: …
```
=> A read timeout (socket.timeout) causes exception
